% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  12pt,
]{book}
\usepackage{amsmath,amssymb}
\usepackage{setspace}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=1in,left=1in,right=1in,bottom=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[]{natbib}
\bibliographystyle{apalike}
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={IOBR Tutorial},
  pdfauthor={Dongqiang Zeng},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{IOBR Tutorial}
\author{Dongqiang Zeng}
\date{2023-08-24}

\usepackage{amsthm}
\newtheorem{theorem}{Theorem}[chapter]
\newtheorem{lemma}{Lemma}[chapter]
\newtheorem{corollary}{Corollary}[chapter]
\newtheorem{proposition}{Proposition}[chapter]
\newtheorem{conjecture}{Conjecture}[chapter]
\theoremstyle{definition}
\newtheorem{definition}{Definition}[chapter]
\theoremstyle{definition}
\newtheorem{example}{Example}[chapter]
\theoremstyle{definition}
\newtheorem{exercise}{Exercise}[chapter]
\theoremstyle{definition}
\newtheorem{hypothesis}{Hypothesis}[chapter]
\theoremstyle{remark}
\newtheorem*{remark}{Remark}
\newtheorem*{solution}{Solution}
\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\setstretch{1.5}
\hypertarget{iobr-introduction}{%
\chapter*{\texorpdfstring{\textbf{IOBR introduction}}{IOBR introduction}}\label{iobr-introduction}}
\addcontentsline{toc}{chapter}{\textbf{IOBR introduction}}

\hypertarget{preface}{%
\section*{Preface}\label{preface}}
\addcontentsline{toc}{section}{Preface}

\begin{figure}

{\centering \includegraphics[width=0.95\linewidth]{./fig/IOBR-Workflow} 

}

\caption{The workflow of IOBR}\label{fig:unnamed-chunk-1}
\end{figure}

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

IOBR is design for \href{https://github.com/IOBR/IOBR}{Immuno-Oncology Biological Research}.
Recent advance in next-generation sequencing has triggered the rapidly accumulating publicly available multi-omics data. The application of integrated omics to exploring robust signatures for clinical translation is increasingly highlighted in immuno-oncology but raises computational and biological challenges. This vignette aims to demonstrate how to utilize the package named IOBR to perform multi-omics immuno-oncology biological research to decode tumor microenvironment and signatures for clinical translation.

This R package integrates 8 published methodologies for decoding tumor microenvironment (TME) contexture: \texttt{CIBERSORT}, \texttt{TIMER}, \texttt{xCell}, \texttt{MCPcounter}, \texttt{ESITMATE}, \texttt{EPIC}, \texttt{IPS}, \texttt{quanTIseq}. Moreover, 255 published signature gene sets were collected by IOBR, involving tumor microenvironment, tumor metabolism, m6A, exosomes, microsatellite instability, and tertiary lymphoid structure. Run the function \texttt{signature\_collection\_citation} to obtain the source papers, and the function \texttt{signature\_collection} returns the detail signature genes of all given signatures. Subsequently, IOBR adopts three computational methods to calculate the signature score, comprising \texttt{PCA}, \texttt{z-score}, and \texttt{ssGSEA}. To note, IOBR collected and employed multiple approaches for variable transition, visualization, batch survival analysis, feature selection, and statistical analysis. Batch analysis and visualization of corresponding results are supported. The details of how IOBR works are described below.

\hypertarget{license}{%
\section{License}\label{license}}

\textbf{IOBR} is released under the GPL v3.0 license. See \href{https://github.com/IOBR/IOBR/blob/master/LICENSE}{LICENSE} for details. The code contained in this book is simultaneously available under the \href{https://www.gnu.org/licenses/why-not-lgpl.html}{GPL license}; this means that you are free to use it in your packages, as long as you cite the source. The online version of this book is licensed under the \href{https://creativecommons.org/licenses/by-nc-sa/4.0/}{Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.}

\hypertarget{publishment}{%
\section{Publishment}\label{publishment}}

Zeng D, Ye Z, Shen R, Yu G, Wu J, Xiong Y,\ldots, Liao W (2021) \textbf{IOBR}: Multi-Omics Immuno-Oncology Biological Research to Decode Tumor Microenvironment and Signatures. \emph{Frontiers in Immunology}. 12:687975. \href{https://www.frontiersin.org/articles/10.3389/fimmu.2021.687975/full}{doi: 10.3389/fimmu.2021.687975}

\hypertarget{reporting-bugs}{%
\section{Reporting bugs}\label{reporting-bugs}}

Please report bugs to the \href{https://github.com/IOBR/IOBR/issues}{Github issues page}

E-mail any questions to \href{mailto:dongqiangzeng0808@gmail.com}{\nolinkurl{dongqiangzeng0808@gmail.com}}

\hypertarget{how-to-install-iobr}{%
\chapter{How to install IOBR}\label{how-to-install-iobr}}

\hypertarget{installing-dependency-packages}{%
\section{Installing Dependency Packages}\label{installing-dependency-packages}}

It is essential that you have R 3.6.3 or above already installed on your computer or server. IOBR is a pipeline that utilizes many other R packages that are currently available from CRAN, Bioconductor and GitHub.

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{requireNamespace}\NormalTok{(}\StringTok{"BiocManager"}\NormalTok{, }\AttributeTok{quietly =} \ConstantTok{TRUE}\NormalTok{)) }\FunctionTok{install.packages}\NormalTok{(}\StringTok{"BiocManager"}\NormalTok{)}
\NormalTok{depens}\OtherTok{\textless{}{-}}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}tibble\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}survival\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}survminer\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}limma\textquotesingle{}}\NormalTok{, }\StringTok{"DESeq2"}\NormalTok{,}\StringTok{"devtools"}\NormalTok{, }\StringTok{\textquotesingle{}limSolve\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}GSVA\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}e1071\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}preprocessCore\textquotesingle{}}\NormalTok{, }
          \StringTok{"devtools"}\NormalTok{, }\StringTok{"tidyHeatmap"}\NormalTok{, }\StringTok{"caret"}\NormalTok{, }\StringTok{"glmnet"}\NormalTok{, }\StringTok{"ppcor"}\NormalTok{,  }\StringTok{"timeROC"}\NormalTok{, }\StringTok{"pracma"}\NormalTok{, }\StringTok{"factoextra"}\NormalTok{, }
          \StringTok{"FactoMineR"}\NormalTok{, }\StringTok{"WGCNA"}\NormalTok{, }\StringTok{"patchwork"}\NormalTok{, }\StringTok{\textquotesingle{}ggplot2\textquotesingle{}}\NormalTok{, }\StringTok{"biomaRt"}\NormalTok{, }\StringTok{\textquotesingle{}ggpubr\textquotesingle{}}\NormalTok{)}
\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(depens))\{}
\NormalTok{  depen}\OtherTok{\textless{}{-}}\NormalTok{depens[i]}
  \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{requireNamespace}\NormalTok{(depen, }\AttributeTok{quietly =} \ConstantTok{TRUE}\NormalTok{))  BiocManager}\SpecialCharTok{::}\FunctionTok{install}\NormalTok{(depen,}\AttributeTok{update =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\hypertarget{installing-iobr}{%
\section{Installing IOBR}\label{installing-iobr}}

Then, you can start to install IOBR from github by typing the following code into your R session:

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{requireNamespace}\NormalTok{(}\StringTok{"IOBR"}\NormalTok{, }\AttributeTok{quietly =} \ConstantTok{TRUE}\NormalTok{))  devtools}\SpecialCharTok{::}\FunctionTok{install\_github}\NormalTok{(}\StringTok{"IOBR/IOBR"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'tidyHeatmap' was built under R version 4.2.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(IOBR)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'tibble' was built under R version 4.2.3
\end{verbatim}

\begin{verbatim}
## Warning: package 'dplyr' was built under R version 4.2.3
\end{verbatim}

\begin{verbatim}
## Warning: package 'ggplot2' was built under R version 4.2.3
\end{verbatim}

\hypertarget{the-main-pipeline-of-iobr}{%
\section{The main pipeline of IOBR}\label{the-main-pipeline-of-iobr}}

\begin{figure}

{\centering \includegraphics[width=92.42in]{./fig/IOBR-Package} 

}

\caption{The main pipeline of IOBR}\label{fig:flowchart}
\end{figure}

\hypertarget{rna-data-preprocessing}{%
\chapter{RNA Data preprocessing}\label{rna-data-preprocessing}}

\hypertarget{library}{%
\section{Library}\label{library}}

Load the IOBR package in your R session after the installation is complete:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(IOBR)}
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(clusterProfiler)}
\end{Highlighting}
\end{Shaded}

\hypertarget{downloading-data-for-example}{%
\section{Downloading data for example}\label{downloading-data-for-example}}

Obtaining data set from GEO \href{https://pubmed.ncbi.nlm.nih.gov/25894828/}{Gastric cancer: GSE62254} using \texttt{GEOquery} R package.

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{requireNamespace}\NormalTok{(}\StringTok{"GEOquery"}\NormalTok{, }\AttributeTok{quietly =} \ConstantTok{TRUE}\NormalTok{))  BiocManager}\SpecialCharTok{::}\FunctionTok{install}\NormalTok{(}\StringTok{"GEOquery"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(}\StringTok{"GEOquery"}\NormalTok{)}
\CommentTok{\# }\AlertTok{NOTE}\CommentTok{: This process may take a few minutes which depends on the internet connection speed. Please wait for its completion.}
\NormalTok{eset\_geo}\OtherTok{\textless{}{-}}\FunctionTok{getGEO}\NormalTok{(}\AttributeTok{GEO     =} \StringTok{"GSE62254"}\NormalTok{, }\AttributeTok{getGPL  =}\NormalTok{ F, }\AttributeTok{destdir =} \StringTok{"./"}\NormalTok{)}
\NormalTok{eset    }\OtherTok{\textless{}{-}}\NormalTok{eset\_geo[[}\DecValTok{1}\NormalTok{]]}
\NormalTok{eset    }\OtherTok{\textless{}{-}}\FunctionTok{exprs}\NormalTok{(eset)}
\NormalTok{eset[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{,}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           GSM1523727 GSM1523728 GSM1523729 GSM1523744 GSM1523745
## 1007_s_at  3.2176645  3.0624323  3.0279131   2.921683  2.8456013
## 1053_at    2.4050109  2.4394879  2.2442708   2.345916  2.4328582
## 117_at     1.4933412  1.8067380  1.5959665   1.839822  1.8326058
## 121_at     2.1965561  2.2812181  2.1865556   2.258599  2.1874363
## 1255_g_at  0.8698382  0.9502466  0.8125414   1.012860  0.9441993
\end{verbatim}

Annotation of genes in the expression matrix and removal of duplicate genes.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load the annotation file \textasciigrave{}anno\_hug133plus2\textasciigrave{} in IOBR.}
\FunctionTok{head}\NormalTok{(anno\_hug133plus2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 2
##   probe_id  symbol 
##   <fct>     <fct>  
## 1 1007_s_at MIR4640
## 2 1053_at   RFC2   
## 3 117_at    HSPA6  
## 4 121_at    PAX8   
## 5 1255_g_at GUCA1A 
## 6 1294_at   MIR5193
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Conduct gene annotation using \textasciigrave{}anno\_hug133plus2\textasciigrave{} file; If identical gene symbols exists, these genes would be ordered by the mean expression levels. The gene symbol with highest mean expression level is selected and remove others. }

\NormalTok{eset}\OtherTok{\textless{}{-}}\FunctionTok{anno\_eset}\NormalTok{(}\AttributeTok{eset       =}\NormalTok{ eset,}
                \AttributeTok{annotation =}\NormalTok{ anno\_hug133plus2,}
                \AttributeTok{symbol     =} \StringTok{"symbol"}\NormalTok{,}
                \AttributeTok{probe      =} \StringTok{"probe\_id"}\NormalTok{,}
                \AttributeTok{method     =} \StringTok{"mean"}\NormalTok{)}
\NormalTok{eset[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              GSM1523727 GSM1523728 GSM1523729
## SH3KBP1        4.327974   4.316195   4.351425
## RPL41          4.246149   4.246808   4.257940
## EEF1A1         4.293762   4.291038   4.262199
## COX2           4.250288   4.283714   4.270508
## LOC101928826   4.219303   4.219670   4.213252
\end{verbatim}

\hypertarget{identifying-outlier-samples}{%
\section{Identifying outlier samples}\label{identifying-outlier-samples}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# source("E:/18{-}Github/Organization/IOBR/R/find\_outlier\_samples.R")}
\NormalTok{res }\OtherTok{\textless{}{-}} \FunctionTok{find\_outlier\_samples}\NormalTok{(}\AttributeTok{eset =}\NormalTok{ eset, }\AttributeTok{project =} \StringTok{"ACRG"}\NormalTok{, }\AttributeTok{show\_plot =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{_main_files/figure-latex/unnamed-chunk-8-1} \end{center}

\begin{verbatim}
## [1] "GSM1523817" "GSM1523858" "GSM1523984" "GSM1523988" "GSM1524030"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{eset1 }\OtherTok{\textless{}{-}}\NormalTok{ eset[, }\SpecialCharTok{!}\FunctionTok{colnames}\NormalTok{(eset)}\SpecialCharTok{\%in\%}\NormalTok{res]}
\end{Highlighting}
\end{Shaded}

\hypertarget{pca-analysis-of-molecular-subtypes}{%
\section{PCA analysis of molecular subtypes}\label{pca-analysis-of-molecular-subtypes}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(}\StringTok{"pdata\_acrg"}\NormalTok{)}
\NormalTok{res}\OtherTok{\textless{}{-}} \FunctionTok{iobr\_pca}\NormalTok{(}\AttributeTok{data       =}\NormalTok{ eset1,}
              \AttributeTok{is.matrix   =} \ConstantTok{TRUE}\NormalTok{,}
              \AttributeTok{scale       =} \ConstantTok{TRUE}\NormalTok{,}
              \AttributeTok{is.log      =} \ConstantTok{FALSE}\NormalTok{,}
              \AttributeTok{pdata       =}\NormalTok{ pdata\_acrg, }
              \AttributeTok{id\_pdata    =} \StringTok{"ID"}\NormalTok{, }
              \AttributeTok{group       =} \StringTok{"Subtype"}\NormalTok{,}
              \AttributeTok{geom.ind    =} \StringTok{"point"}\NormalTok{, }
              \AttributeTok{cols        =} \StringTok{"normal"}\NormalTok{,}
              \AttributeTok{palette     =} \StringTok{"jama"}\NormalTok{, }
              \AttributeTok{repel       =} \ConstantTok{FALSE}\NormalTok{,}
              \AttributeTok{ncp         =} \DecValTok{5}\NormalTok{,}
              \AttributeTok{axes        =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{),}
              \AttributeTok{addEllipses =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##       CIN       EBV       EMT        GS       MSI MSS/TP53- MSS/TP53+ 
##         0         0        42         0        68       106        79 
## [1] ">>-- colors for PCA: #5f75ae" ">>-- colors for PCA: #64a841"
## [3] ">>-- colors for PCA: #e5486e" ">>-- colors for PCA: #de8e06"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{_main_files/figure-latex/unnamed-chunk-9-1} \end{center}

\hypertarget{batch-effect-correction}{%
\section{Batch effect correction}\label{batch-effect-correction}}

Obtaining another data set from GEO \href{https://www.ncbi.nlm.nih.gov/pubmed/24935174/}{Gastric cancer: GSE57303} using \texttt{GEOquery} R package.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# }\AlertTok{NOTE}\CommentTok{: This process may take a few minutes which depends on the internet connection speed. Please wait for its completion.}
\NormalTok{eset\_geo}\OtherTok{\textless{}{-}}\FunctionTok{getGEO}\NormalTok{(}\AttributeTok{GEO     =} \StringTok{"GSE57303"}\NormalTok{, }\AttributeTok{getGPL  =}\NormalTok{ F, }\AttributeTok{destdir =} \StringTok{"./"}\NormalTok{)}
\NormalTok{eset2    }\OtherTok{\textless{}{-}}\NormalTok{eset\_geo[[}\DecValTok{1}\NormalTok{]]}
\NormalTok{eset2    }\OtherTok{\textless{}{-}}\FunctionTok{exprs}\NormalTok{(eset2)}
\NormalTok{eset2[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{,}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           GSM1379261 GSM1379262 GSM1379263 GSM1379264 GSM1379265
## 1007_s_at    8.34746    9.67994    8.62643    8.59301    8.63046
## 1053_at      5.07972    4.46377    5.29685    5.78983    4.33359
## 117_at       5.65558    4.48732    4.21615    5.47984    5.20816
## 121_at       5.95123    7.09056    6.19903    5.89872    5.91323
## 1255_g_at    1.66923    1.98758    1.73083    1.56687    1.63332
\end{verbatim}

Annotation of genes in the expression matrix and removal of duplicate genes.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{eset2}\OtherTok{\textless{}{-}}\FunctionTok{anno\_eset}\NormalTok{(}\AttributeTok{eset       =}\NormalTok{ eset2,}
                 \AttributeTok{annotation =}\NormalTok{ anno\_hug133plus2,}
                 \AttributeTok{symbol     =} \StringTok{"symbol"}\NormalTok{,}
                 \AttributeTok{probe      =} \StringTok{"probe\_id"}\NormalTok{,}
                 \AttributeTok{method     =} \StringTok{"mean"}\NormalTok{)}
\NormalTok{eset2[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         GSM1379261 GSM1379262 GSM1379263 GSM1379264 GSM1379265
## ND4        13.1695    13.1804    13.0600    12.4544    13.0457
## ATP6       13.1433    13.0814    13.0502    12.4831    13.1168
## SH3KBP1    12.9390    13.1620    12.9773    12.8745    13.1169
## COX2       13.0184    13.0489    12.8621    12.7489    12.9732
## RPL41      13.0201    12.6034    12.7929    13.0153    12.9404
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{eset\_com }\OtherTok{\textless{}{-}} \FunctionTok{remove\_batcheffect}\NormalTok{( }\AttributeTok{eset1       =}\NormalTok{ eset1,  }
                                \AttributeTok{eset2       =}\NormalTok{ eset2,   }
                                \AttributeTok{eset3       =} \ConstantTok{NULL}\NormalTok{,}
                                \AttributeTok{id\_type     =} \StringTok{"symbol"}\NormalTok{,}
                                \AttributeTok{data\_type   =} \StringTok{"array"}\NormalTok{, }
                                \AttributeTok{cols        =} \StringTok{"normal"}\NormalTok{, }
                                \AttributeTok{palette     =} \StringTok{"jama"}\NormalTok{, }
                                \AttributeTok{log2        =} \ConstantTok{TRUE}\NormalTok{, }
                                \AttributeTok{check\_eset  =} \ConstantTok{TRUE}\NormalTok{,}
                                \AttributeTok{adjust\_eset =} \ConstantTok{TRUE}\NormalTok{,}
                                \AttributeTok{repel       =} \ConstantTok{FALSE}\NormalTok{,}
                                \AttributeTok{path        =} \StringTok{"result"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## eset1 eset2 
##   295    70 
## [1] ">>-- colors for PCA: #5f75ae" ">>-- colors for PCA: #64a841"
## 
## eset1 eset2 
##   295    70 
## [1] ">>-- colors for PCA: #5f75ae" ">>-- colors for PCA: #64a841"
\end{verbatim}

\begin{center}\includegraphics{_main_files/figure-latex/unnamed-chunk-12-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(eset\_com)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 21752   365
\end{verbatim}

\hypertarget{tumor-ecosystem-analysis}{%
\chapter{Tumor ecosystem analysis}\label{tumor-ecosystem-analysis}}

\hypertarget{determine-tme-subtype-of-gastric-cancer-using-tmeclassifier}{%
\section{Determine TME subtype of gastric cancer using TMEclassifier}\label{determine-tme-subtype-of-gastric-cancer-using-tmeclassifier}}

加载TME分类器R包\href{https://github.com/LiaoWJLab/TMEclassifier}{TMEclassifier}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(TMEclassifier)}
\NormalTok{tme }\OtherTok{\textless{}{-}} \FunctionTok{tme\_classifier}\NormalTok{(}\AttributeTok{eset =}\NormalTok{ eset1, }\AttributeTok{scale =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Step-1: Expression data preprocessing...
## Step-2: TME deconvolution...
## Step-3: Predicting TME phenotypes...
## [10:58:25] WARNING: amalgamation/../src/learner.cc:1040: 
##   If you are loading a serialized model (like pickle in Python, RDS in R) generated by
##   older XGBoost, please export the model by calling `Booster.save_model` from that version
##   first, then load it back in current version. See:
## 
##     https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html
## 
##   for more details about differences between saving model and serializing.
## 
## [10:58:25] WARNING: amalgamation/../src/learner.cc:749: Found JSON model saved before XGBoost 1.6, please save the model using current version again. The support for old JSON model will be discontinued in XGBoost 2.3.
## >>>--- DONE!
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(tme}\SpecialCharTok{$}\NormalTok{TMEcluster)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  IA  IE  IS 
## 106  94  95
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(tme)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           ID         IE        IS         IA TMEcluster
## 1 GSM1523727 0.21034596 0.1089890 0.68066503         IA
## 2 GSM1523728 0.01008306 0.1120120 0.87790490         IA
## 3 GSM1523729 0.85603729 0.1119151 0.03204757         IE
## 4 GSM1523744 0.05645817 0.0770771 0.86646473         IA
## 5 GSM1523745 0.05785239 0.8128097 0.12933787         IS
## 6 GSM1523746 0.55697476 0.3827613 0.06026396         IE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(tme}\SpecialCharTok{$}\NormalTok{TMEcluster)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  IA  IE  IS 
## 106  94  95
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(tme)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           ID         IE        IS         IA TMEcluster
## 1 GSM1523727 0.21034596 0.1089890 0.68066503         IA
## 2 GSM1523728 0.01008306 0.1120120 0.87790490         IA
## 3 GSM1523729 0.85603729 0.1119151 0.03204757         IE
## 4 GSM1523744 0.05645817 0.0770771 0.86646473         IA
## 5 GSM1523745 0.05785239 0.8128097 0.12933787         IS
## 6 GSM1523746 0.55697476 0.3827613 0.06026396         IE
\end{verbatim}

\hypertarget{deg-analysis}{%
\section{DEG analysis}\label{deg-analysis}}

选择IA和IE分型进行差异分析

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pdata }\OtherTok{\textless{}{-}}\NormalTok{ tme[}\SpecialCharTok{!}\NormalTok{tme}\SpecialCharTok{$}\NormalTok{TMEcluster}\SpecialCharTok{==}\StringTok{"IS"}\NormalTok{, ]}
\NormalTok{deg  }\OtherTok{\textless{}{-}}   \FunctionTok{iobr\_deg}\NormalTok{(}\AttributeTok{eset         =}\NormalTok{ eset,}
                   \AttributeTok{annoation    =} \ConstantTok{NULL}\NormalTok{,}
                   \AttributeTok{pdata        =}\NormalTok{ pdata,}
                   \AttributeTok{group\_id     =} \StringTok{"TMEcluster"}\NormalTok{,}
                   \AttributeTok{pdata\_id     =} \StringTok{"ID"}\NormalTok{,}
                   \AttributeTok{array        =} \ConstantTok{TRUE}\NormalTok{,}
                   \AttributeTok{method       =} \StringTok{"limma"}\NormalTok{,}
                   \AttributeTok{contrast     =} \FunctionTok{c}\NormalTok{(}\StringTok{"deg\_group"}\NormalTok{,}\StringTok{"IA"}\NormalTok{,}\StringTok{"IE"}\NormalTok{),}
                   \AttributeTok{path         =} \ConstantTok{NULL}\NormalTok{,}
                   \AttributeTok{padj\_cutoff  =} \FloatTok{0.01}\NormalTok{,}
                   \AttributeTok{logfc\_cutoff =} \FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'limma'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:BiocGenerics':
## 
##     plotMA
\end{verbatim}

\begin{verbatim}
## group1 = IA
\end{verbatim}

\begin{verbatim}
## group2 = IE
\end{verbatim}

\begin{verbatim}
## # A tibble: 6 x 11
##   symbol  log2FoldChange AveExpr     t   pvalue     padj     B sigORnot    label
##   <chr>            <dbl>   <dbl> <dbl>    <dbl>    <dbl> <dbl> <chr>       <chr>
## 1 TMEM100         -0.755    1.83 -14.0 1.54e-31 3.35e-27  60.9 Down_regul~ Both 
## 2 ABCA8           -0.923    1.89 -12.9 3.18e-28 3.46e-24  53.4 Down_regul~ Both 
## 3 HHIP            -0.625    1.74 -12.4 1.52e-26 1.10e-22  49.6 Down_regul~ Both 
## 4 ADH1B           -0.901    1.84 -12.2 4.71e-26 2.09e-22  48.5 Down_regul~ Both 
## 5 LMNB2            0.285    2.26  12.2 4.80e-26 2.09e-22  48.5 NOT         Sign~
## 6 FCER1A          -0.552    1.57 -12.0 2.34e-25 7.27e-22  46.9 Down_regul~ Both 
## # i 2 more variables: IA <dbl>, IE <dbl>
\end{verbatim}

\hypertarget{gsea-analysis-of-degs}{%
\section{GSEA analysis of DEGs}\label{gsea-analysis-of-degs}}

选择IOBR的signature collection

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(deg)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 11
##   symbol  log2FoldChange AveExpr     t   pvalue     padj     B sigORnot    label
##   <chr>            <dbl>   <dbl> <dbl>    <dbl>    <dbl> <dbl> <chr>       <chr>
## 1 TMEM100         -0.755    1.83 -14.0 1.54e-31 3.35e-27  60.9 Down_regul~ Both 
## 2 ABCA8           -0.923    1.89 -12.9 3.18e-28 3.46e-24  53.4 Down_regul~ Both 
## 3 HHIP            -0.625    1.74 -12.4 1.52e-26 1.10e-22  49.6 Down_regul~ Both 
## 4 ADH1B           -0.901    1.84 -12.2 4.71e-26 2.09e-22  48.5 Down_regul~ Both 
## 5 LMNB2            0.285    2.26  12.2 4.80e-26 2.09e-22  48.5 NOT         Sign~
## 6 FCER1A          -0.552    1.57 -12.0 2.34e-25 7.27e-22  46.9 Down_regul~ Both 
## # i 2 more variables: IA <dbl>, IE <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sig\_list }\OtherTok{\textless{}{-}}\NormalTok{ signature\_collection[}\FunctionTok{c}\NormalTok{(}\StringTok{"TMEscoreB\_CIR"}\NormalTok{, }\StringTok{"TMEscoreA\_CIR"}\NormalTok{, }\StringTok{"DNA\_replication"}\NormalTok{, }\StringTok{"Base\_excision\_repair"}\NormalTok{,}
                                   \StringTok{"Pan\_F\_TBRs"}\NormalTok{, }\StringTok{"TGFb.myCAF"}\NormalTok{, }\StringTok{"Ferroptosis"}\NormalTok{, }\StringTok{"TLS\_Nature"}\NormalTok{, }\StringTok{"Glycolysis"}\NormalTok{)]}
\NormalTok{sig\_list}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $TMEscoreB_CIR
##   [1] "DCN"          "SEPP1"        "ACTA2"        "SPARCL1"      "BEX3"        
##   [6] "MYLK"         "AKR1C1"       "TIMP2"        "MXRA7"        "C11orf96"    
##  [11] "CAV1"         "PDGFRA"       "FHL1"         "MGP"          "EID1"        
##  [16] "LOC101930400" "DST"          "GREM1"        "FERMT2"       "TNC"         
##  [21] "CYBRD1"       "LTBP1"        "ACTG2"        "TMEM47"       "SERPINE2"    
##  [26] "ANTXR2"       "GNG11"        "TAGLN"        "GSTA4"        "PKIG"        
##  [31] "MAOA"         "PTRF"         "FAM3B"        "PBX1"         "WLS"         
##  [36] "SELM"         "SVIL"         "MYH11"        "AGT"          "SPON1"       
##  [41] "TGFB1I1"      "PDLIM3"       "PDK4"         "SYNPO2"       "MSRB3"       
##  [46] "PROS1"        "EDNRA"        "AKAP12"       "PSD3"         "TNS1"        
##  [51] "JAM3"         "PDZRN3"       "DDR2"         "HMGCS2"       "SGCE"        
##  [56] "MRVI1"        "WFDC1"        "FBLN1"        "FMO5"         "MAOB"        
##  [61] "AMOTL1"       "AKT3"         "CNRIP1"       "CPE"          "MAP1B"       
##  [66] "RBP1"         "GNAI1"        "FOXF2"        "SORBS2"       "ZCCHC24"     
##  [71] "ZNF704"       "ARMCX1"       "DIXDC1"       "SSTR1"        "THRB"        
##  [76] "C3orf70"      "PKIB"         "CNN1"         "SYTL5"        "DACT1"       
##  [81] "SYNPO"        "GAS1"         "DPYSL3"       "CCDC80"       "TSPYL5"      
##  [86] "DCHS1"        "SOBP"         "AOC3"         "NDN"          "FGF7P3"      
##  [91] "SMAD9"        "MCC"          "CLMP"         "MYL9"         "RBP4"        
##  [96] "PLN"          "SPOCK1"       "COL14A1"      "CRYAB"        "SRPX"        
## [101] "EML1"         "RERG"         "PPP1R3C"      "LOC100506718" "CH25H"       
## [106] "HSPB8"        "PID1"         "TTC28"        "STON1"        "ABCG2"       
## [111] "ZSCAN18"      "SCIN"         "C14orf132"    "TMEM55A"      "WASF3"       
## [116] "PAPLN"        "COLEC12"      "ACKR1"        "TMEM150C"     "RAI2"        
## [121] "TSPAN7"       "MRGPRF"       "ABCA8"        "CHIC1"        "NBEA"        
## [126] "FAM13C"       "SETBP1"       "LDOC1"        "TMEM100"      "LOC101930349"
## [131] "PRICKLE2"     "TSPAN18"      "FABP4"        "ARHGEF26"     "ERICH5"      
## [136] "MYOCD"        "BEX2"         "PPP1R14A"     "FGF13"        "RUNX1T1"     
## [141] "MAGI2-AS3"    "LINC01279"    "REEP1"        "PLAC9"        "MYEF2"       
## [146] "PRKD1"        "RGN"          "CLDN11"       "ANK2"         "ESRRG"       
## [151] "SYNC"         "ZNF667-AS1"   "FGF7"         "SFRP1"        "HMCN1"       
## [156] "TCEAL7"       "OGN"          "MAGI2"        "MIR100HG"     "FILIP1"      
## [161] "LOC100507334" "ANKRD6"       "PLEKHH2"      "ZNF542P"      "ARMCX4"      
## [166] "NOV"          "DCLK1"        "ARHGAP28"     "C2orf40"      "TRHDE"       
## [171] "EPHA7"        "SCRG1"        "ZNF677"       "ZFPM2"        "PEG3"        
## [176] "SERP2"        "ZNF415"       "MAMDC2"       "RBM24"        "MEOX2"       
## 
## $TMEscoreA_CIR
##  [1] "HLA-DPB1"       "UBD"            "LOC100509457"   "WARS"          
##  [5] "TAP1"           "HLA-DMA"        "TRIM22"         "PSAT1"         
##  [9] "CXCL10"         "SOCS3"          "CXCL9"          "PBK"           
## [13] "CCL4"           "CCL5"           "BCL2A1"         "TRBC1"         
## [17] "IDO1"           "NFE2L3"         "CCL3L3"         "DTL"           
## [21] "MMP9"           "SLC2A3"         "ZNF367"         "RCC1"          
## [25] "STIL"           "TRAC"           "HELLS"          "GZMB"          
## [29] "RTEL1-TNFRSF6B" "CXCL11"         "GBP5"           "CD2"           
## [33] "CDCA2"          "CDT1"           "TNFAIP2"        "TYMP"          
## [37] "MICB"           "SLC2A14"        "GZMK"           "CD8A"          
## [41] "CENPH"          "MND1"           "BATF2"          "BRIP1"         
## [45] "E2F7"           "KIF18A"         "AIM2"           "ETV7"          
## [49] "ITK"            "GNLY"           "GPR171"         "WDHD1"         
## [53] "GBP4"           "MB21D1"         "NLRP3"          "MCEMP1"        
## [57] "POLR3G"         "NLRC3"          "KLRC2"          "CLEC5A"        
## [61] "ARHGAP11A"      "GPR84"          "IFNG"           "ZBED2"         
## 
## $DNA_replication
##  [1] "RNASEH2A" "POLD3"    "DNA2"     "FEN1"     "POLA2"    "RNASEH1" 
##  [7] "RPA4"     "LIG1"     "MCM2"     "MCM3"     "MCM4"     "MCM5"    
## [13] "MCM6"     "MCM7"     "PCNA"     "POLE3"    "POLA1"    "POLD1"   
## [19] "POLD2"    "POLE"     "POLE2"    "PRIM1"    "PRIM2"    "POLE4"   
## [25] "POLD4"    "RFC1"     "RFC2"     "RFC3"     "RFC4"     "RFC5"    
## [31] "RPA1"     "RPA2"     "RPA3"     "SSBP1"    "RNASEH2B" "RNASEH2C"
## 
## $Base_excision_repair
##  [1] "PARP2" "PARP3" "POLD3" "PARP1" "PARP4" "FEN1"  "SMUG1" "NEIL2" "APEX2"
## [10] "POLL"  "HMGB1" "APEX1" "LIG1"  "LIG3"  "MPG"   "MUTYH" "NTHL1" "OGG1" 
## [19] "PCNA"  "POLE3" "POLB"  "POLD1" "POLD2" "POLE"  "POLE2" "NEIL3" "POLE4"
## [28] "POLD4" "UNG"   "XRCC1" "NEIL1" "MBD4" 
## 
## $Pan_F_TBRs
##  [1] "ACTA2"    "ACTG2"    "ADAM12"   "ADAM19"   "CNN1"     "COL4A1"  
##  [7] "CTGF"     "CTPS1"    "FAM101B"  "FSTL3"    "HSPB1"    "IGFBP3"  
## [13] "PXDC1"    "SEMA7A"   "SH3PXD2A" "TAGLN"    "TGFBI"    "TNS1"    
## [19] "TPM1"    
## 
## $TGFb.myCAF
##  [1] "CST1"    "LAMP5"   "LOXL1"   "EDNRA"   "TGFB1"   "TGFB3"   "TNN"    
##  [8] "CST2"    "HES4"    "COL10A1" "ELN"     "THBS4"   "NKD2"    "OLFM2"  
## [15] "COL6A3"  "LRRC17"  "COL3A1"  "THY1"    "HTRA3"   "TMEM204" "11-Sep" 
## [22] "COMP"    "TNFAIP6" "ID4"     "GGT5"    "INAFM1"  "CILP"    "OLFML2B"
## 
## $Ferroptosis
##  [1] "ACSL4"      "AKR1C1-3"   "ALOXs"      "ATP5G3"     "CARS"      
##  [6] "CBS"        "CD44v"      "CHAC1"      "CISD1"      "CS"        
## [11] "DPP4"       "FANCD2"     "GCLC/GCLM"  "GLS2"       "GPX4"      
## [16] "GSS"        "HMGCR"      "HSPB1/5"    "KOD"        "LPCAT3"    
## [21] "MT1G"       "NCOA4"      "NFE2L2"     "PTGS2"      "RPL8"      
## [26] "SAT1"       "SLC7A11"    "SQS"        "TFRC"       "TP53"      
## [31] "TTC35/EMC2" "MESH1"     
## 
## $TLS_Nature
## [1] "CD79B"  "CD1D"   "CCR6"   "LAT"    "SKAP1"  "CETP"   "EIF1AY" "RBP5"  
## [9] "PTGDS" 
## 
## $Glycolysis
##  [1] "ACSS1"   "ACSS2"   "ADH1A"   "ADH1B"   "ADH1C"   "ADH4"    "ADH5"   
##  [8] "ADH6"    "ADH7"    "ADPGK"   "AKR1A1"  "ALDH1A3" "ALDH1B1" "ALDH2"  
## [15] "ALDH3A1" "ALDH3A2" "ALDH3B1" "ALDH3B2" "ALDH7A1" "ALDH9A1" "ALDOA"  
## [22] "ALDOB"   "ALDOC"   "BPGM"    "DLAT"    "DLD"     "ENO1"    "ENO2"   
## [29] "ENO3"    "FBP1"    "FBP2"    "G6PC"    "G6PC2"   "GALM"    "GAPDH"  
## [36] "GAPDHS"  "GCK"     "GPI"     "HK1"     "HK2"     "HK3"     "HKDC1"  
## [43] "LDHA"    "LDHAL6A" "LDHAL6B" "LDHB"    "LDHC"    "PANK1"   "PCK1"   
## [50] "PCK2"    "PDHA1"   "PDHA2"   "PDHB"    "PFKFB1"  "PFKFB2"  "PFKFB3" 
## [57] "PFKFB4"  "PFKL"    "PFKM"    "PFKP"    "PGAM1"   "PGAM2"   "PGAM4"  
## [64] "PGK1"    "PGK2"    "PGM1"    "PGM2"    "PKLR"    "PKM"     "SLC2A2" 
## [71] "TPI1"
\end{verbatim}

结果有报错，寻找原因中！！！

\hypertarget{deg-analysis-1}{%
\section{DEG analysis}\label{deg-analysis-1}}

使用\texttt{find\_markers\_in\_bulk}寻找TME分型相关的差异基因

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(Seurat)}
\NormalTok{res }\OtherTok{\textless{}{-}} \FunctionTok{find\_markers\_in\_bulk}\NormalTok{(}\AttributeTok{pdata      =}\NormalTok{ tme, }
                            \AttributeTok{eset       =}\NormalTok{ eset, }
                            \AttributeTok{group      =} \StringTok{"TMEcluster"}\NormalTok{, }
                            \AttributeTok{nfeatures  =} \DecValTok{2000}\NormalTok{, }
                            \AttributeTok{top\_n      =} \DecValTok{20}\NormalTok{, }
                            \AttributeTok{thresh.use =} \FloatTok{0.15}\NormalTok{, }
                            \AttributeTok{only.pos   =} \ConstantTok{TRUE}\NormalTok{, }
                            \AttributeTok{min.pct    =} \FloatTok{0.10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  IA  IE  IS 
## 106  94  95 
## # A tibble: 56 x 7
## # Groups:   cluster [3]
##       p_val avg_log2FC pct.1 pct.2 p_val_adj cluster gene  
##       <dbl>      <dbl> <dbl> <dbl>     <dbl> <fct>   <chr> 
##  1 4.66e-19      0.208     1     1  1.01e-14 IA      IFNG  
##  2 7.41e-18      0.170     1     1  1.61e-13 IA      CXCL10
##  3 1.21e-15      0.177     1     1  2.62e-11 IA      GZMB  
##  4 1.34e-15      0.247     1     1  2.91e-11 IA      CXCL11
##  5 5.33e-15      0.166     1     1  1.16e-10 IA      CXCL9 
##  6 6.17e-15      0.158     1     1  1.34e-10 IA      POLR3G
##  7 3.06e-14      0.214     1     1  6.66e-10 IA      IDO1  
##  8 1.95e-13      0.179     1     1  4.24e- 9 IA      GBP4  
##  9 4.17e-13      0.150     1     1  9.07e- 9 IA      ZBED2 
## 10 3.74e-11      0.153     1     1  8.13e- 7 IA      GNLY  
## # i 46 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{top15 }\OtherTok{\textless{}{-}}\NormalTok{  res}\SpecialCharTok{$}\NormalTok{top\_markers }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::} \FunctionTok{group\_by}\NormalTok{(cluster) }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{top\_n}\NormalTok{(}\DecValTok{15}\NormalTok{, avg\_log2FC)}
\NormalTok{top15}\SpecialCharTok{$}\NormalTok{gene}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "IFNG"           "CXCL10"         "GZMB"           "CXCL11"        
##  [5] "CXCL9"          "POLR3G"         "IDO1"           "GBP4"          
##  [9] "GNLY"           "PLEKHS1"        "KLRC2"          "VSNL1"         
## [13] "AIM2"           "SLCO1B3"        "COL11A1"        "TMEM100"       
## [17] "ADH1B"          "ABCA8"          "MAMDC2"         "SCN7A"         
## [21] "C7"             "C2orf40"        "LIPF"           "PGA4"          
## [25] "SCGB2A1"        "FUT9"           "GKN1"           "GKN2"          
## [29] "OGN"            "GIF"            "IL1A"           "EREG"          
## [33] "PPBP"           "IL11"           "CXCL6"          "PI15"          
## [37] "TNFRSF11B"      "PROK2"          "CLEC5A"         "MAGEA10-MAGEA5"
## [41] "MAGEA4"         "MAGEA12"        "MAGEA6"         "MAGEA2B"       
## [45] "REG1B"
\end{verbatim}

使用\texttt{Seurat}的\texttt{DoHeatmap}进行热图的可视化

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#定义分型对应的颜色}
\NormalTok{cols }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}\#2692a4\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}\#fc0d3a\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}\#ffbe0b\textquotesingle{}}\NormalTok{)}
\NormalTok{p1 }\OtherTok{\textless{}{-}} \FunctionTok{DoHeatmap}\NormalTok{(res}\SpecialCharTok{$}\NormalTok{sce, top15}\SpecialCharTok{$}\NormalTok{gene, }\AttributeTok{group.colors =}\NormalTok{ cols )}\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_gradientn}\NormalTok{(}\AttributeTok{colours =} \FunctionTok{rev}\NormalTok{(}\FunctionTok{colorRampPalette}\NormalTok{(RColorBrewer}\SpecialCharTok{::}\FunctionTok{brewer.pal}\NormalTok{(}\DecValTok{11}\NormalTok{,}\StringTok{"RdBu"}\NormalTok{))(}\DecValTok{256}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

提取表达矩阵中的变量与TME分型数据进行合并

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{input }\OtherTok{\textless{}{-}} \FunctionTok{combine\_pd\_eset}\NormalTok{(}\AttributeTok{eset =}\NormalTok{ eset, }\AttributeTok{pdata =}\NormalTok{ tme, }\AttributeTok{feas =}\NormalTok{ top15}\SpecialCharTok{$}\NormalTok{gene, }\AttributeTok{scale =}\NormalTok{ T)}

\NormalTok{p2 }\OtherTok{\textless{}{-}} \FunctionTok{sig\_box}\NormalTok{(input, }\AttributeTok{variable =} \StringTok{"TMEcluster"}\NormalTok{, }\AttributeTok{signature =} \StringTok{"IFNG"}\NormalTok{, }\AttributeTok{jitter =} \ConstantTok{TRUE}\NormalTok{,}
              \AttributeTok{cols =}\NormalTok{  cols, }\AttributeTok{show\_pvalue =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{size\_of\_pvalue =} \DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 8
##   .y.       group1 group2        p    p.adj p.format p.signif method  
##   <chr>     <chr>  <chr>     <dbl>    <dbl> <chr>    <chr>    <chr>   
## 1 signature IA     IE     7.08e-16 2.10e-15 7.1e-16  ****     Wilcoxon
## 2 signature IA     IS     5.12e-13 1   e-12 5.1e-13  ****     Wilcoxon
## 3 signature IE     IS     9.36e- 2 9.4 e- 2 0.094    ns       Wilcoxon
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p3 }\OtherTok{\textless{}{-}} \FunctionTok{sig\_box}\NormalTok{(input, }\AttributeTok{variable =} \StringTok{"TMEcluster"}\NormalTok{, }\AttributeTok{signature =} \StringTok{"IL1A"}\NormalTok{,  }
              \AttributeTok{jitter =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{cols =}\NormalTok{  cols, }\AttributeTok{show\_pvalue =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{size\_of\_pvalue =} \DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 8
##   .y.       group1 group2        p    p.adj p.format p.signif method  
##   <chr>     <chr>  <chr>     <dbl>    <dbl> <chr>    <chr>    <chr>   
## 1 signature IA     IE     1.17e- 9 2.3 e- 9 1.2e-09  ****     Wilcoxon
## 2 signature IA     IS     6.19e- 7 6.20e- 7 6.2e-07  ****     Wilcoxon
## 3 signature IE     IS     4.51e-19 1.4 e-18 < 2e-16  ****     Wilcoxon
\end{verbatim}

合并以上获得的结果图

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{requireNamespace}\NormalTok{(}\StringTok{"patchwork"}\NormalTok{, }\AttributeTok{quietly =} \ConstantTok{TRUE}\NormalTok{))   }\FunctionTok{install.packages}\NormalTok{(}\StringTok{"patchwork"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(patchwork)}
\NormalTok{p }\OtherTok{\textless{}{-}}\NormalTok{ (p1}\SpecialCharTok{|}\NormalTok{p2}\SpecialCharTok{/}\NormalTok{p3) }\SpecialCharTok{+} \FunctionTok{plot\_layout}\NormalTok{(}\AttributeTok{widths =} \FunctionTok{c}\NormalTok{(}\FloatTok{2.3}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\NormalTok{p }\SpecialCharTok{+} \FunctionTok{plot\_annotation}\NormalTok{(}\AttributeTok{tag\_levels =} \StringTok{\textquotesingle{}A\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_main_files/figure-latex/unnamed-chunk-20-1.pdf}

\hypertarget{identifying-signatures-associated-with-tme-clusters}{%
\section{Identifying signatures associated with TME clusters}\label{identifying-signatures-associated-with-tme-clusters}}

Calculate TME associated signatures-(through PCA method).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sig\_tme}\OtherTok{\textless{}{-}}\FunctionTok{calculate\_sig\_score}\NormalTok{(}\AttributeTok{pdata           =} \ConstantTok{NULL}\NormalTok{,}
                             \AttributeTok{eset            =}\NormalTok{ eset,}
                             \AttributeTok{signature       =}\NormalTok{ signature\_collection,}
                             \AttributeTok{method          =} \StringTok{"pca"}\NormalTok{,}
                             \AttributeTok{mini\_gene\_count =} \DecValTok{2}\NormalTok{)}
\NormalTok{sig\_tme }\OtherTok{\textless{}{-}} \FunctionTok{t}\NormalTok{(}\FunctionTok{column\_to\_rownames}\NormalTok{(sig\_tme, }\AttributeTok{var =} \StringTok{"ID"}\NormalTok{))}
\NormalTok{sig\_tme[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                   GSM1523727 GSM1523728 GSM1523729
## CD_8_T_effector   -2.5513794  0.7789141 -2.1770675
## DDR               -0.8747614  0.7425162 -1.3272054
## APM                1.1098368  2.1988688 -0.9516419
## Immune_Checkpoint -2.3701787  0.9455120 -1.4844104
## CellCycle_Reg      0.1063358  0.7583302 -0.3649795
\end{verbatim}

寻找与TMEcluster相关的特征变量

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res }\OtherTok{\textless{}{-}} \FunctionTok{find\_markers\_in\_bulk}\NormalTok{(}\AttributeTok{pdata =}\NormalTok{ tme, }\AttributeTok{eset =}\NormalTok{ sig\_tme, }\AttributeTok{group =} \StringTok{"TMEcluster"}\NormalTok{, }\AttributeTok{nfeatures =} \DecValTok{1000}\NormalTok{, }\AttributeTok{top\_n =} \DecValTok{20}\NormalTok{, }\AttributeTok{min.pct =} \FloatTok{0.10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  IA  IE  IS 
## 106  94  95 
## # A tibble: 60 x 7
## # Groups:   cluster [3]
##       p_val avg_log2FC pct.1 pct.2 p_val_adj cluster gene                       
##       <dbl>      <dbl> <dbl> <dbl>     <dbl> <fct>   <chr>                      
##  1 2.73e-18      17.8  0.792 0.365  6.98e-16 IA      Base-excision-repair       
##  2 8.18e-18       3.64 0.698 0.323  2.09e-15 IA      IFNG-signature-Ayers-et-al 
##  3 9.03e-18       8.94 0.84  0.381  2.31e-15 IA      Mismatch-Repair            
##  4 9.73e-18       4.17 0.821 0.402  2.49e-15 IA      Th2-cells-Bindea-et-al     
##  5 1.20e-16       3.97 0.821 0.381  3.08e-14 IA      Folate-One-Carbon-Metaboli~
##  6 1.14e-15       4.36 0.811 0.354  2.91e-13 IA      Homologous-recombination   
##  7 2.13e-14       3.09 0.83  0.397  5.45e-12 IA      Purine-Biosynthesis        
##  8 3.61e-14       4.20 0.67  0.28   9.25e-12 IA      CD-8-T-effector            
##  9 1.49e-13       2.70 0.708 0.344  3.82e-11 IA      Th1-cells-Bindea-et-al     
## 10 7.03e-13       2.61 0.792 0.429  1.80e-10 IA      TIP-Release-of-cancer-cell~
## # i 50 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{top15 }\OtherTok{\textless{}{-}}\NormalTok{  res}\SpecialCharTok{$}\NormalTok{top\_markers }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{ dplyr}\SpecialCharTok{::} \FunctionTok{group\_by}\NormalTok{(cluster) }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{top\_n}\NormalTok{(}\DecValTok{15}\NormalTok{, avg\_log2FC)}

\NormalTok{p1 }\OtherTok{\textless{}{-}} \FunctionTok{DoHeatmap}\NormalTok{(res}\SpecialCharTok{$}\NormalTok{sce, top15}\SpecialCharTok{$}\NormalTok{gene, }\AttributeTok{group.colors =}\NormalTok{ cols)}\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_gradientn}\NormalTok{(}\AttributeTok{colours =} \FunctionTok{rev}\NormalTok{(}\FunctionTok{colorRampPalette}\NormalTok{(RColorBrewer}\SpecialCharTok{::}\FunctionTok{brewer.pal}\NormalTok{(}\DecValTok{11}\NormalTok{,}\StringTok{"RdBu"}\NormalTok{))(}\DecValTok{256}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

可视化结果：选择特征变量

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{top15}\SpecialCharTok{$}\NormalTok{gene  }\OtherTok{\textless{}{-}} \FunctionTok{gsub}\NormalTok{(top15}\SpecialCharTok{$}\NormalTok{gene, }\AttributeTok{pattern =} \StringTok{"}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{{-}"}\NormalTok{, }\AttributeTok{replacement =} \StringTok{"}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{\_"}\NormalTok{)}
\NormalTok{input }\OtherTok{\textless{}{-}} \FunctionTok{combine\_pd\_eset}\NormalTok{(}\AttributeTok{eset =}\NormalTok{ sig\_tme, }\AttributeTok{pdata =}\NormalTok{ tme, }\AttributeTok{feas =}\NormalTok{ top15}\SpecialCharTok{$}\NormalTok{gene, }\AttributeTok{scale =}\NormalTok{ T)}

\NormalTok{p2 }\OtherTok{\textless{}{-}} \FunctionTok{sig\_box}\NormalTok{(input, }\AttributeTok{variable =} \StringTok{"TMEcluster"}\NormalTok{, }\AttributeTok{signature =} \StringTok{"IFNG\_signature\_Ayers\_et\_al"}\NormalTok{, }\AttributeTok{jitter =} \ConstantTok{TRUE}\NormalTok{,}
              \AttributeTok{cols =}\NormalTok{  cols, }\AttributeTok{show\_pvalue =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{size\_of\_pvalue =} \DecValTok{4}\NormalTok{, }\AttributeTok{size\_of\_font =} \DecValTok{6}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 8
##   .y.       group1 group2        p    p.adj p.format p.signif method  
##   <chr>     <chr>  <chr>     <dbl>    <dbl> <chr>    <chr>    <chr>   
## 1 signature IA     IE     3.34e-12 6.70e-12 3.3e-12  ****     Wilcoxon
## 2 signature IA     IS     7.93e-15 2.40e-14 7.9e-15  ****     Wilcoxon
## 3 signature IE     IS     2.54e- 1 2.5 e- 1 0.25     ns       Wilcoxon
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p3 }\OtherTok{\textless{}{-}} \FunctionTok{sig\_box}\NormalTok{(input, }\AttributeTok{variable =} \StringTok{"TMEcluster"}\NormalTok{, }\AttributeTok{signature =} \StringTok{"Neutrophils\_Bindea\_et\_al"}\NormalTok{,  }
              \AttributeTok{jitter =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{cols =}\NormalTok{  cols, }\AttributeTok{show\_pvalue =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{size\_of\_pvalue =} \DecValTok{4}\NormalTok{, }\AttributeTok{size\_of\_font =} \DecValTok{6}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 8
##   .y.       group1 group2        p  p.adj p.format p.signif method  
##   <chr>     <chr>  <chr>     <dbl>  <dbl> <chr>    <chr>    <chr>   
## 1 signature IA     IE     0.0222   0.044  0.02217  *        Wilcoxon
## 2 signature IA     IS     0.0333   0.044  0.03326  *        Wilcoxon
## 3 signature IE     IS     0.000133 0.0004 0.00013  ***      Wilcoxon
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p }\OtherTok{\textless{}{-}}\NormalTok{ (p1}\SpecialCharTok{|}\NormalTok{p2}\SpecialCharTok{/}\NormalTok{p3) }\SpecialCharTok{+} \FunctionTok{plot\_layout}\NormalTok{(}\AttributeTok{widths =} \FunctionTok{c}\NormalTok{(}\FloatTok{2.3}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\NormalTok{p }\SpecialCharTok{+} \FunctionTok{plot\_annotation}\NormalTok{(}\AttributeTok{tag\_levels =} \StringTok{\textquotesingle{}A\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_main_files/figure-latex/unnamed-chunk-24-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(survminer)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'survminer'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:survival':
## 
##     myeloma
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(pdata\_acrg, }\AttributeTok{package =} \StringTok{"IOBR"}\NormalTok{)}
\NormalTok{input }\OtherTok{\textless{}{-}} \FunctionTok{merge}\NormalTok{(pdata\_acrg, input, }\AttributeTok{by =} \StringTok{"ID"}\NormalTok{)}
\NormalTok{p1}\OtherTok{\textless{}{-}}\FunctionTok{surv\_group}\NormalTok{(}\AttributeTok{input\_pdata       =}\NormalTok{ input,}
               \AttributeTok{target\_group      =} \StringTok{"TMEcluster"}\NormalTok{,}
               \AttributeTok{ID                =} \StringTok{"ID"}\NormalTok{,}
               \AttributeTok{reference\_group   =} \StringTok{"High"}\NormalTok{,}
               \AttributeTok{project           =} \StringTok{"ACRG"}\NormalTok{,}
               \AttributeTok{cols              =}\NormalTok{ cols, }
               \AttributeTok{time              =} \StringTok{"OS\_time"}\NormalTok{,}
               \AttributeTok{status            =} \StringTok{"OS\_status"}\NormalTok{,}
               \AttributeTok{time\_type         =} \StringTok{"month"}\NormalTok{,}
               \AttributeTok{save\_path         =} \StringTok{"result"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## >>> Dataset's survival follow up time is range between 1 to 105.7 months
\end{verbatim}

\begin{verbatim}
##  IA  IE  IS 
## 106  94  95
\end{verbatim}

\begin{verbatim}
## 1069495
\end{verbatim}

\begin{verbatim}
##   Maximum of follow up time is 105.7 months; and will be divided into 6 sections;
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p1}
\end{Highlighting}
\end{Shaded}

\includegraphics{_main_files/figure-latex/unnamed-chunk-25-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p1}\OtherTok{\textless{}{-}} \FunctionTok{percent\_bar\_plot}\NormalTok{(input, }\AttributeTok{x =} \StringTok{"TMEcluster"}\NormalTok{ , }\AttributeTok{y =} \StringTok{"Subtype"}\NormalTok{, }\AttributeTok{palette =} \StringTok{"jama"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 12 x 5
## # Groups:   TMEcluster [3]
##    TMEcluster Subtype    Freq  Prop count
##    <chr>      <fct>     <dbl> <dbl> <dbl>
##  1 IA         EMT           6  0.06   106
##  2 IA         MSI          49  0.46   106
##  3 IA         MSS/TP53-    27  0.25   106
##  4 IA         MSS/TP53+    24  0.23   106
##  5 IE         EMT          22  0.23    94
##  6 IE         MSI           3  0.03    94
##  7 IE         MSS/TP53-    40  0.43    94
##  8 IE         MSS/TP53+    29  0.31    94
##  9 IS         EMT          14  0.15    95
## 10 IS         MSI          16  0.17    95
## 11 IS         MSS/TP53-    39  0.41    95
## 12 IS         MSS/TP53+    26  0.27    95
## [1] "'#374E55FF', '#DF8F44FF', '#00A1D5FF', '#B24745FF', '#79AF97FF', '#6A6599FF', '#80796BFF'"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p2}\OtherTok{\textless{}{-}} \FunctionTok{percent\_bar\_plot}\NormalTok{(input, }\AttributeTok{x =} \StringTok{"TMEcluster"}\NormalTok{ , }\AttributeTok{y =} \StringTok{"Lauren"}\NormalTok{, }\AttributeTok{palette =} \StringTok{"jama"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 9 x 5
## # Groups:   TMEcluster [3]
##   TMEcluster Lauren      Freq  Prop count
##   <chr>      <fct>      <dbl> <dbl> <dbl>
## 1 IA         Diffuse       33  0.31   106
## 2 IA         Intestinal    60  0.57   106
## 3 IA         Mixed         13  0.12   106
## 4 IE         Diffuse       58  0.62    94
## 5 IE         Intestinal    32  0.34    94
## 6 IE         Mixed          4  0.04    94
## 7 IS         Diffuse       39  0.41    95
## 8 IS         Intestinal    54  0.57    95
## 9 IS         Mixed          2  0.02    95
## [1] "'#374E55FF', '#DF8F44FF', '#00A1D5FF', '#B24745FF', '#79AF97FF', '#6A6599FF', '#80796BFF'"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p3}\OtherTok{\textless{}{-}} \FunctionTok{percent\_bar\_plot}\NormalTok{(input, }\AttributeTok{x =} \StringTok{"TMEcluster"}\NormalTok{ , }\AttributeTok{y =} \StringTok{"TMEscore\_binary"}\NormalTok{, }\AttributeTok{palette =} \StringTok{"jama"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 7 x 5
## # Groups:   TMEcluster [3]
##   TMEcluster TMEscore_binary  Freq  Prop count
##   <chr>      <fct>           <dbl> <dbl> <dbl>
## 1 IA         High               60  0.57   106
## 2 IA         Low                46  0.43   106
## 3 IE         High                5  0.05    94
## 4 IE         Low                89  0.95    94
## 5 IS         High                6  0.06    95
## 6 IS         Low                88  0.93    95
## 7 IS         <NA>                1  0.01    95
## [1] "'#374E55FF', '#DF8F44FF', '#00A1D5FF', '#B24745FF', '#79AF97FF', '#6A6599FF', '#80796BFF'"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p1}\SpecialCharTok{|}\NormalTok{p2}\SpecialCharTok{|}\NormalTok{p3}
\end{Highlighting}
\end{Shaded}

\includegraphics{_main_files/figure-latex/unnamed-chunk-27-1.pdf}

\hypertarget{signatures-and-relevant-phenotypes}{%
\chapter{Signatures and relevant phenotypes}\label{signatures-and-relevant-phenotypes}}

\hypertarget{loading-packages}{%
\section{Loading packages}\label{loading-packages}}

Load the IOBR package in your R session after the installation is complete:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(IOBR)}
\FunctionTok{library}\NormalTok{(survminer)}
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\hypertarget{downloading-data-for-example-1}{%
\section{Downloading data for example}\label{downloading-data-for-example-1}}

Obtaining data set from GEO \href{https://pubmed.ncbi.nlm.nih.gov/25894828/}{Gastric cancer: GSE62254} using \texttt{GEOquery} R package.

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{requireNamespace}\NormalTok{(}\StringTok{"GEOquery"}\NormalTok{, }\AttributeTok{quietly =} \ConstantTok{TRUE}\NormalTok{))  BiocManager}\SpecialCharTok{::}\FunctionTok{install}\NormalTok{(}\StringTok{"GEOquery"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(}\StringTok{"GEOquery"}\NormalTok{)}
\CommentTok{\# }\AlertTok{NOTE}\CommentTok{: This process may take a few minutes which depends on the internet connection speed. Please wait for its completion.}
\NormalTok{eset\_geo }\OtherTok{\textless{}{-}} \FunctionTok{getGEO}\NormalTok{(}\AttributeTok{GEO     =} \StringTok{"GSE62254"}\NormalTok{, }\AttributeTok{getGPL  =}\NormalTok{ F, }\AttributeTok{destdir =} \StringTok{"./"}\NormalTok{)}
\NormalTok{eset    }\OtherTok{\textless{}{-}}\NormalTok{eset\_geo[[}\DecValTok{1}\NormalTok{]]}
\NormalTok{eset    }\OtherTok{\textless{}{-}}\FunctionTok{exprs}\NormalTok{(eset)}
\NormalTok{eset[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{,}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           GSM1523727 GSM1523728 GSM1523729 GSM1523744 GSM1523745
## 1007_s_at  3.2176645  3.0624323  3.0279131   2.921683  2.8456013
## 1053_at    2.4050109  2.4394879  2.2442708   2.345916  2.4328582
## 117_at     1.4933412  1.8067380  1.5959665   1.839822  1.8326058
## 121_at     2.1965561  2.2812181  2.1865556   2.258599  2.1874363
## 1255_g_at  0.8698382  0.9502466  0.8125414   1.012860  0.9441993
\end{verbatim}

Annotation of genes in the expression matrix and removal of duplicate genes.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load the annotation file \textasciigrave{}anno\_hug133plus2\textasciigrave{} in IOBR.}
\FunctionTok{head}\NormalTok{(anno\_hug133plus2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 2
##   probe_id  symbol 
##   <fct>     <fct>  
## 1 1007_s_at MIR4640
## 2 1053_at   RFC2   
## 3 117_at    HSPA6  
## 4 121_at    PAX8   
## 5 1255_g_at GUCA1A 
## 6 1294_at   MIR5193
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Conduct gene annotation using \textasciigrave{}anno\_hug133plus2\textasciigrave{} file; If identical gene symbols exists, these genes would be ordered by the mean expression levels. The gene symbol with highest mean expression level is selected and remove others. }

\NormalTok{eset}\OtherTok{\textless{}{-}}\FunctionTok{anno\_eset}\NormalTok{(}\AttributeTok{eset       =}\NormalTok{ eset,}
                \AttributeTok{annotation =}\NormalTok{ anno\_hug133plus2,}
                \AttributeTok{symbol     =} \StringTok{"symbol"}\NormalTok{,}
                \AttributeTok{probe      =} \StringTok{"probe\_id"}\NormalTok{,}
                \AttributeTok{method     =} \StringTok{"mean"}\NormalTok{)}
\NormalTok{eset[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              GSM1523727 GSM1523728 GSM1523729
## SH3KBP1        4.327974   4.316195   4.351425
## RPL41          4.246149   4.246808   4.257940
## EEF1A1         4.293762   4.291038   4.262199
## COX2           4.250288   4.283714   4.270508
## LOC101928826   4.219303   4.219670   4.213252
\end{verbatim}

\hypertarget{signature-score-estimation}{%
\section{Signature score estimation}\label{signature-score-estimation}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sig\_tme}\OtherTok{\textless{}{-}}\FunctionTok{calculate\_sig\_score}\NormalTok{(}\AttributeTok{pdata           =} \ConstantTok{NULL}\NormalTok{,}
                             \AttributeTok{eset            =}\NormalTok{ eset,}
                             \AttributeTok{signature       =}\NormalTok{ signature\_collection,}
                             \AttributeTok{method          =} \StringTok{"pca"}\NormalTok{,}
                             \AttributeTok{mini\_gene\_count =} \DecValTok{2}\NormalTok{)}
\NormalTok{sig\_tme }\OtherTok{\textless{}{-}} \FunctionTok{t}\NormalTok{(}\FunctionTok{column\_to\_rownames}\NormalTok{(sig\_tme, }\AttributeTok{var =} \StringTok{"ID"}\NormalTok{))}
\NormalTok{sig\_tme[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                   GSM1523727 GSM1523728 GSM1523729
## CD_8_T_effector   -2.5513794  0.7789141 -2.1770675
## DDR               -0.8747614  0.7425162 -1.3272054
## APM                1.1098368  2.1988688 -0.9516419
## Immune_Checkpoint -2.3701787  0.9455120 -1.4844104
## CellCycle_Reg      0.1063358  0.7583302 -0.3649795
\end{verbatim}

\hypertarget{identifying-features-associated-with-survival}{%
\section{Identifying features associated with survival}\label{identifying-features-associated-with-survival}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(}\StringTok{"pdata\_acrg"}\NormalTok{)}
\NormalTok{input }\OtherTok{\textless{}{-}} \FunctionTok{combine\_pd\_eset}\NormalTok{(}\AttributeTok{eset =}\NormalTok{ sig\_tme, }\AttributeTok{pdata =}\NormalTok{ pdata\_acrg, }\AttributeTok{scale =}\NormalTok{ T)}
\NormalTok{res}\OtherTok{\textless{}{-}} \FunctionTok{batch\_surv}\NormalTok{(}\AttributeTok{pdata    =}\NormalTok{ input,}
                 \AttributeTok{time     =} \StringTok{"OS\_time"}\NormalTok{, }
                 \AttributeTok{status   =} \StringTok{"OS\_status"}\NormalTok{, }
                 \AttributeTok{variable =} \FunctionTok{colnames}\NormalTok{(input)[}\DecValTok{69}\SpecialCharTok{:}\FunctionTok{ncol}\NormalTok{(input)])}
\FunctionTok{head}\NormalTok{(res)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 5
##   ID                           P    HR CI_low_0.95 CI_up_0.95
##   <chr>                    <dbl> <dbl>       <dbl>      <dbl>
## 1 Folate_biosynthesis   1.00e-10 0.579       0.490      0.683
## 2 TMEscore_CIR          1.32e- 9 0.640       0.554      0.739
## 3 Glycogen_Biosynthesis 3.24e- 9 1.52        1.32       1.74 
## 4 Pan_F_TBRs            6.33e- 9 1.55        1.34       1.80 
## 5 TMEscoreB_CIR         7.17e- 9 1.52        1.32       1.75 
## 6 TMEscore_plus         8.08e- 9 0.638       0.547      0.743
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res}\OtherTok{\textless{}{-}}\NormalTok{ res[}\FunctionTok{nchar}\NormalTok{(res}\SpecialCharTok{$}\NormalTok{ID)}\SpecialCharTok{\textless{}=}\DecValTok{28}\NormalTok{, ]}
\NormalTok{p1}\OtherTok{\textless{}{-}} \FunctionTok{sig\_forest}\NormalTok{(res, }\AttributeTok{signature =} \StringTok{"ID"}\NormalTok{, }\AttributeTok{n =} \DecValTok{20}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{_main_files/figure-latex/unnamed-chunk-32-1} \end{center}

\hypertarget{visulization-using-heatmap}{%
\section{Visulization using heatmap}\label{visulization-using-heatmap}}

Signatures和分子分型之间的关系
使用\texttt{IOBR}的\texttt{sig\_heatmap}进行热图的可视化

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p2 }\OtherTok{\textless{}{-}} \FunctionTok{sig\_heatmap}\NormalTok{(}\AttributeTok{input         =}\NormalTok{ input, }
                  \AttributeTok{features      =}\NormalTok{ res}\SpecialCharTok{$}\NormalTok{ID[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{20}\NormalTok{],}
                  \AttributeTok{group         =} \StringTok{"Subtype"}\NormalTok{, }
                  \AttributeTok{palette\_group =} \StringTok{"jama"}\NormalTok{, }
                  \AttributeTok{palette       =} \DecValTok{6}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{_main_files/figure-latex/unnamed-chunk-33-1} \end{center}

\hypertarget{focus-on-target-signatures}{%
\section{Focus on target signatures}\label{focus-on-target-signatures}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p1 }\OtherTok{\textless{}{-}} \FunctionTok{sig\_box}\NormalTok{(}\AttributeTok{data           =}\NormalTok{ input, }
              \AttributeTok{signature      =} \StringTok{"Glycogen\_Biosynthesis"}\NormalTok{,}
              \AttributeTok{variable       =} \StringTok{"Subtype"}\NormalTok{,}
              \AttributeTok{jitter          =} \ConstantTok{TRUE}\NormalTok{,}
              \AttributeTok{cols           =} \ConstantTok{NULL}\NormalTok{,}
              \AttributeTok{palette        =} \StringTok{"jama"}\NormalTok{,}
              \AttributeTok{show\_pvalue    =} \ConstantTok{TRUE}\NormalTok{,}
              \AttributeTok{size\_of\_pvalue =} \DecValTok{5}\NormalTok{,}
              \AttributeTok{hjust          =} \DecValTok{1}\NormalTok{, }
              \AttributeTok{angle\_x\_text   =} \DecValTok{60}\NormalTok{, }
              \AttributeTok{size\_of\_font   =} \DecValTok{8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 8
##   .y.       group1    group2           p    p.adj p.format p.signif method  
##   <chr>     <chr>     <chr>        <dbl>    <dbl> <chr>    <chr>    <chr>   
## 1 signature EMT       MSI       5.39e-15 3.20e-14 5.4e-15  ****     Wilcoxon
## 2 signature EMT       MSS/TP53- 5.53e-13 2.8 e-12 5.5e-13  ****     Wilcoxon
## 3 signature EMT       MSS/TP53+ 1.90e-12 7.6 e-12 1.9e-12  ****     Wilcoxon
## 4 signature MSI       MSS/TP53- 1.14e- 3 3.4 e- 3 0.0011   **       Wilcoxon
## 5 signature MSI       MSS/TP53+ 7.05e- 3 1.4 e- 2 0.0071   **       Wilcoxon
## 6 signature MSS/TP53- MSS/TP53+ 7.16e- 1 7.2 e- 1 0.7161   ns       Wilcoxon
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p2 }\OtherTok{\textless{}{-}} \FunctionTok{sig\_box}\NormalTok{(}\AttributeTok{data           =}\NormalTok{ input, }
              \AttributeTok{signature      =} \StringTok{"Pan\_F\_TBRs"}\NormalTok{,}
              \AttributeTok{variable       =} \StringTok{"Subtype"}\NormalTok{,}
              \AttributeTok{jitter          =} \ConstantTok{TRUE}\NormalTok{,}
              \AttributeTok{cols           =} \ConstantTok{NULL}\NormalTok{,}
              \AttributeTok{palette        =} \StringTok{"jama"}\NormalTok{,}
              \AttributeTok{show\_pvalue    =} \ConstantTok{TRUE}\NormalTok{,}
              \AttributeTok{angle\_x\_text   =} \DecValTok{60}\NormalTok{, }
              \AttributeTok{hjust          =} \DecValTok{1}\NormalTok{, }
              \AttributeTok{size\_of\_pvalue =} \DecValTok{5}\NormalTok{, }
              \AttributeTok{size\_of\_font   =} \DecValTok{8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 8
##   .y.       group1    group2           p    p.adj p.format p.signif method  
##   <chr>     <chr>     <chr>        <dbl>    <dbl> <chr>    <chr>    <chr>   
## 1 signature EMT       MSI       7.98e-17 3.20e-16 <2e-16   ****     Wilcoxon
## 2 signature EMT       MSS/TP53- 1.70e-17 1   e-16 <2e-16   ****     Wilcoxon
## 3 signature EMT       MSS/TP53+ 2.57e-17 1.3 e-16 <2e-16   ****     Wilcoxon
## 4 signature MSI       MSS/TP53- 1.32e- 2 4   e- 2 0.013    *        Wilcoxon
## 5 signature MSI       MSS/TP53+ 6.99e- 2 1.4 e- 1 0.070    ns       Wilcoxon
## 6 signature MSS/TP53- MSS/TP53+ 4.02e- 1 4   e- 1 0.402    ns       Wilcoxon
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p3 }\OtherTok{\textless{}{-}} \FunctionTok{sig\_box}\NormalTok{(}\AttributeTok{data           =}\NormalTok{ input, }
              \AttributeTok{signature      =} \StringTok{"Immune\_Checkpoint"}\NormalTok{,}
              \AttributeTok{variable       =} \StringTok{"Subtype"}\NormalTok{,}
              \AttributeTok{jitter          =} \ConstantTok{TRUE}\NormalTok{,}
              \AttributeTok{cols           =} \ConstantTok{NULL}\NormalTok{,}
              \AttributeTok{palette        =} \StringTok{"jama"}\NormalTok{,}
              \AttributeTok{show\_pvalue    =} \ConstantTok{TRUE}\NormalTok{,}
              \AttributeTok{angle\_x\_text   =} \DecValTok{60}\NormalTok{, }
              \AttributeTok{hjust          =} \DecValTok{1}\NormalTok{, }
              \AttributeTok{size\_of\_pvalue =} \DecValTok{5}\NormalTok{, }
              \AttributeTok{size\_of\_font   =} \DecValTok{8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 8
##   .y.       group1    group2           p        p.adj p.format p.signif method  
##   <chr>     <chr>     <chr>        <dbl>        <dbl> <chr>    <chr>    <chr>   
## 1 signature EMT       MSI       2.20e- 2 0.044        0.0220   *        Wilcoxon
## 2 signature EMT       MSS/TP53- 2.11e- 3 0.0085       0.0021   **       Wilcoxon
## 3 signature EMT       MSS/TP53+ 4.03e- 1 0.4          0.4026   ns       Wilcoxon
## 4 signature MSI       MSS/TP53- 9.13e-10 0.0000000055 9.1e-10  ****     Wilcoxon
## 5 signature MSI       MSS/TP53+ 5.03e- 4 0.0025       0.0005   ***      Wilcoxon
## 6 signature MSS/TP53- MSS/TP53+ 4.82e- 3 0.014        0.0048   **       Wilcoxon
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p1}\SpecialCharTok{|}\NormalTok{p2}\SpecialCharTok{|}\NormalTok{p3}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{_main_files/figure-latex/unnamed-chunk-35-1} \end{center}

\hypertarget{survival-analysis}{%
\section{Survival analysis}\label{survival-analysis}}

Signature的多种分层下的生存分析

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res }\OtherTok{\textless{}{-}}       \FunctionTok{sig\_surv\_plot}\NormalTok{(}\AttributeTok{input\_pdata       =}\NormalTok{ input, }
                           \AttributeTok{signature         =} \StringTok{"Glycogen\_Biosynthesis"}\NormalTok{,}
                           \AttributeTok{cols              =} \ConstantTok{NULL}\NormalTok{, }
                           \AttributeTok{palette           =} \StringTok{"jco"}\NormalTok{,}
                           \AttributeTok{project           =} \StringTok{"ACRG"}\NormalTok{,}
                           \AttributeTok{time              =} \StringTok{"OS\_time"}\NormalTok{,}
                           \AttributeTok{status            =} \StringTok{"OS\_status"}\NormalTok{,}
                           \AttributeTok{time\_type         =} \StringTok{"month"}\NormalTok{,}
                           \AttributeTok{save\_path         =} \StringTok{"result"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           ID   time status Glycogen_Biosynthesis group3 group2 bestcutoff
## 1 GSM1523727  88.73      0            -0.3612213 Middle    Low        Low
## 2 GSM1523728  88.23      0            -0.6926726    Low    Low        Low
## 3 GSM1523729  88.23      0            -0.9388531    Low    Low        Low
## 4 GSM1523744 105.70      0            -1.1825136    Low    Low        Low
## 5 GSM1523745 105.53      0            -0.3034304 Middle    Low        Low
## 6 GSM1523746  25.50      1             0.7517934   High   High       High
\end{verbatim}

\begin{verbatim}
## [1] ">>>>>>>>>"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res}\SpecialCharTok{$}\NormalTok{plots}
\end{Highlighting}
\end{Shaded}

\includegraphics{_main_files/figure-latex/unnamed-chunk-36-1.pdf}

Signature在预测生存上的ROC

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p1}\OtherTok{\textless{}{-}} \FunctionTok{roc\_time}\NormalTok{(}\AttributeTok{input      =}\NormalTok{ input,  }
             \AttributeTok{vars       =} \StringTok{"Glycogen\_Biosynthesis"}\NormalTok{, }
             \AttributeTok{time       =} \StringTok{"OS\_time"}\NormalTok{,}
             \AttributeTok{status     =} \StringTok{"OS\_status"}\NormalTok{, }
             \AttributeTok{time\_point =} \FunctionTok{c}\NormalTok{(}\DecValTok{12}\NormalTok{, }\DecValTok{24}\NormalTok{, }\DecValTok{36}\NormalTok{), }
             \AttributeTok{time\_type  =} \StringTok{"month"}\NormalTok{,}
             \AttributeTok{palette    =} \StringTok{"jama"}\NormalTok{,}
             \AttributeTok{cols       =} \StringTok{"normal"}\NormalTok{,}
             \AttributeTok{seed       =} \DecValTok{1234}\NormalTok{, }
             \AttributeTok{show\_col   =} \ConstantTok{FALSE}\NormalTok{, }
             \AttributeTok{path       =} \StringTok{"result"}\NormalTok{, }
             \AttributeTok{main       =} \StringTok{"OS"}\NormalTok{,}
             \AttributeTok{index      =} \DecValTok{1}\NormalTok{,}
             \AttributeTok{fig.type   =} \StringTok{"pdf"}\NormalTok{,}
             \AttributeTok{width      =} \DecValTok{5}\NormalTok{,}
             \AttributeTok{height     =} \FloatTok{5.2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] ">>>-- Range of Time: "
## [1]   1.0 105.7
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p2}\OtherTok{\textless{}{-}} \FunctionTok{roc\_time}\NormalTok{(}\AttributeTok{input      =}\NormalTok{ input,  }
             \AttributeTok{vars       =} \StringTok{"Glycogen\_Biosynthesis"}\NormalTok{, }
             \AttributeTok{time       =} \StringTok{"RFS\_time"}\NormalTok{,}
             \AttributeTok{status     =} \StringTok{"RFS\_status"}\NormalTok{, }
             \AttributeTok{time\_point =} \FunctionTok{c}\NormalTok{(}\DecValTok{12}\NormalTok{, }\DecValTok{24}\NormalTok{, }\DecValTok{36}\NormalTok{), }
             \AttributeTok{time\_type  =} \StringTok{"month"}\NormalTok{,}
             \AttributeTok{palette    =} \StringTok{"jama"}\NormalTok{,}
             \AttributeTok{cols       =} \StringTok{"normal"}\NormalTok{,}
             \AttributeTok{seed       =} \DecValTok{1234}\NormalTok{, }
             \AttributeTok{show\_col   =} \ConstantTok{FALSE}\NormalTok{, }
             \AttributeTok{path       =} \StringTok{"result"}\NormalTok{, }
             \AttributeTok{main       =} \StringTok{"OS"}\NormalTok{,}
             \AttributeTok{index      =} \DecValTok{1}\NormalTok{,}
             \AttributeTok{fig.type   =} \StringTok{"pdf"}\NormalTok{,}
             \AttributeTok{width      =} \DecValTok{5}\NormalTok{,}
             \AttributeTok{height     =} \FloatTok{5.2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] ">>>-- Range of Time: "
## [1]   0.10 100.87
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p1}\SpecialCharTok{|}\NormalTok{p2}
\end{Highlighting}
\end{Shaded}

\includegraphics{_main_files/figure-latex/unnamed-chunk-37-1.pdf}

\hypertarget{batch-correlation-analysis}{%
\section{Batch correlation analysis}\label{batch-correlation-analysis}}

寻找与目标signature相关的基因或者signatures

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res }\OtherTok{\textless{}{-}} \FunctionTok{batch\_cor}\NormalTok{(}\AttributeTok{data =}\NormalTok{ input, }\AttributeTok{target =} \StringTok{"Glycogen\_Biosynthesis"}\NormalTok{, }\AttributeTok{feature =} \FunctionTok{colnames}\NormalTok{(input)[}\DecValTok{69}\SpecialCharTok{:}\FunctionTok{ncol}\NormalTok{(input)])}
\FunctionTok{head}\NormalTok{(res)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 6
##   sig_names                         p.value statistic    p.adj log10pvalue stars
##   <chr>                               <dbl>     <dbl>    <dbl>       <dbl> <fct>
## 1 TMEscoreB_CIR                    8.89e-42     0.678 2.27e-39        41.1 **** 
## 2 Glycine__Serine_and_Threonine_M~ 7.49e-40    -0.666 9.54e-38        39.1 **** 
## 3 Ether_Lipid_Metabolism           3.84e-39     0.662 3.27e-37        38.4 **** 
## 4 MDSC_Peng_et_al                  1.13e-38     0.659 7.21e-37        37.9 **** 
## 5 Glycerophospholipid_Metabolism   8.72e-38    -0.653 4.44e-36        37.1 **** 
## 6 TIP_Release_of_cancer_cell_anti~ 2.32e-37    -0.650 9.86e-36        36.6 ****
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p1}\OtherTok{\textless{}{-}} \FunctionTok{get\_cor}\NormalTok{(}\AttributeTok{eset =}\NormalTok{ sig\_tme, }\AttributeTok{pdata =}\NormalTok{ pdata\_acrg, }\AttributeTok{var1 =} \StringTok{"Glycogen\_Biosynthesis"}\NormalTok{, }\AttributeTok{var2 =} \StringTok{"TMEscore\_CIR"}\NormalTok{, }\AttributeTok{subtype =} \StringTok{"Subtype"}\NormalTok{, }\AttributeTok{palette =} \StringTok{"aaas"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Spearman's rank correlation rho
## 
## data:  data[, var1] and data[, var2]
## S = 7282858, p-value < 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##        rho 
## -0.6184309 
## 
## [1] ">>>--- The exact p value is: 4.78971420439895e-33"
##       EMT       MSI MSS/TP53- MSS/TP53+ 
##        46        68       107        79
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p2}\OtherTok{\textless{}{-}} \FunctionTok{get\_cor}\NormalTok{(}\AttributeTok{eset =}\NormalTok{ sig\_tme, }\AttributeTok{pdata =}\NormalTok{ pdata\_acrg, }\AttributeTok{var1 =} \StringTok{"Glycogen\_Biosynthesis"}\NormalTok{, }\AttributeTok{var2 =} \StringTok{"TGFb.myCAF"}\NormalTok{, }\AttributeTok{subtype =} \StringTok{"Subtype"}\NormalTok{, }\AttributeTok{palette =} \StringTok{"aaas"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Spearman's rank correlation rho
## 
## data:  data[, var1] and data[, var2]
## S = 2471758, p-value < 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## 0.4507143 
## 
## [1] ">>>--- The exact p value is: 2.04505761057615e-16"
##       EMT       MSI MSS/TP53- MSS/TP53+ 
##        46        68       107        79
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p1}\SpecialCharTok{|}\NormalTok{p2}
\end{Highlighting}
\end{Shaded}

\includegraphics{_main_files/figure-latex/unnamed-chunk-40-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{feas1 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Glycogen\_Biosynthesis"}\NormalTok{, }\StringTok{"Ferroptosis"}\NormalTok{)}
\NormalTok{feas2 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Glutathione\_Metabolism"}\NormalTok{, }\StringTok{"TMEscore\_CIR"}\NormalTok{, }\StringTok{"Purine\_Metabolism"}\NormalTok{, }\StringTok{"ICB\_resistance\_Peng\_et\_al"}\NormalTok{, }\StringTok{"Interleukins\_Li\_et\_al"}\NormalTok{, }\StringTok{"TLS\_Nature"}\NormalTok{)}
\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{get\_cor\_matrix}\NormalTok{(}\AttributeTok{data           =}\NormalTok{ input, }
                    \AttributeTok{feas1          =}\NormalTok{ feas2, }
                    \AttributeTok{feas2          =}\NormalTok{ feas1,}
                    \AttributeTok{method         =} \StringTok{"pearson"}\NormalTok{,}
                    \AttributeTok{font.size.star =} \DecValTok{8}\NormalTok{, }
                    \AttributeTok{font.size      =} \DecValTok{15}\NormalTok{, }
                    \AttributeTok{fill\_by\_cor    =} \ConstantTok{FALSE}\NormalTok{, }
                    \AttributeTok{round.num      =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_main_files/figure-latex/unnamed-chunk-41-1.pdf}

\hypertarget{visulization-of-correlations}{%
\section{Visulization of correlations}\label{visulization-of-correlations}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{input2 }\OtherTok{\textless{}{-}} \FunctionTok{combine\_pd\_eset}\NormalTok{(}\AttributeTok{eset =}\NormalTok{ eset, }\AttributeTok{pdata =}\NormalTok{  input[, }\FunctionTok{c}\NormalTok{(}\StringTok{"ID"}\NormalTok{, }\StringTok{"Glycogen\_Biosynthesis"}\NormalTok{, }\StringTok{"TLS\_Nature"}\NormalTok{, }\StringTok{"Ferroptosis"}\NormalTok{)])}
\NormalTok{feas1 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Glycogen\_Biosynthesis"}\NormalTok{,}\StringTok{"TLS\_Nature"}\NormalTok{, }\StringTok{"Ferroptosis"}\NormalTok{)}
\NormalTok{feas2 }\OtherTok{\textless{}{-}}\NormalTok{ signature\_collection}\SpecialCharTok{$}\NormalTok{CD\_8\_T\_effector}
\NormalTok{feas2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "CD8A"   "GZMA"   "GZMB"   "IFNG"   "CXCL9"  "CXCL10" "PRF1"   "TBX21"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{get\_cor\_matrix}\NormalTok{(}\AttributeTok{data           =}\NormalTok{ input2, }
                    \AttributeTok{feas1          =}\NormalTok{ feas2, }
                    \AttributeTok{feas2          =}\NormalTok{ feas1,}
                    \AttributeTok{method         =} \StringTok{"pearson"}\NormalTok{,}
                    \AttributeTok{scale          =}\NormalTok{ T, }
                    \AttributeTok{font.size.star =} \DecValTok{8}\NormalTok{, }
                    \AttributeTok{font.size      =} \DecValTok{15}\NormalTok{, }
                    \AttributeTok{fill\_by\_cor    =} \ConstantTok{FALSE}\NormalTok{, }
                    \AttributeTok{round.num      =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_main_files/figure-latex/unnamed-chunk-42-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{get\_cor\_matrix}\NormalTok{(}\AttributeTok{data           =}\NormalTok{ input2, }
                    \AttributeTok{feas1          =}\NormalTok{ feas2, }
                    \AttributeTok{feas2          =}\NormalTok{ feas1,}
                    \AttributeTok{method         =} \StringTok{"pearson"}\NormalTok{,}
                    \AttributeTok{scale          =}\NormalTok{ T, }
                    \AttributeTok{font.size.star =} \DecValTok{8}\NormalTok{, }
                    \AttributeTok{font.size      =} \DecValTok{15}\NormalTok{, }
                    \AttributeTok{fill\_by\_cor    =} \ConstantTok{TRUE}\NormalTok{, }
                    \AttributeTok{round.num      =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{_main_files/figure-latex/unnamed-chunk-43-1.pdf}

\hypertarget{tme-deconvolution}{%
\chapter{TME deconvolution}\label{tme-deconvolution}}

\hypertarget{loading-packages-1}{%
\section{Loading packages}\label{loading-packages-1}}

Load the IOBR package in your R session after the installation is complete:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(IOBR)}
\FunctionTok{library}\NormalTok{(survminer)}
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\hypertarget{downloading-data-for-example-2}{%
\section{Downloading data for example}\label{downloading-data-for-example-2}}

Obtaining data set from GEO \href{https://pubmed.ncbi.nlm.nih.gov/25894828/}{Gastric cancer: GSE62254} using \texttt{GEOquery} R package.

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{requireNamespace}\NormalTok{(}\StringTok{"GEOquery"}\NormalTok{, }\AttributeTok{quietly =} \ConstantTok{TRUE}\NormalTok{))  BiocManager}\SpecialCharTok{::}\FunctionTok{install}\NormalTok{(}\StringTok{"GEOquery"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(}\StringTok{"GEOquery"}\NormalTok{)}
\CommentTok{\# }\AlertTok{NOTE}\CommentTok{: This process may take a few minutes which depends on the internet connection speed. Please wait for its completion.}
\NormalTok{eset\_geo}\OtherTok{\textless{}{-}}\FunctionTok{getGEO}\NormalTok{(}\AttributeTok{GEO     =} \StringTok{"GSE62254"}\NormalTok{, }\AttributeTok{getGPL  =}\NormalTok{ F, }\AttributeTok{destdir =} \StringTok{"./"}\NormalTok{)}
\NormalTok{eset    }\OtherTok{\textless{}{-}}\NormalTok{eset\_geo[[}\DecValTok{1}\NormalTok{]]}
\NormalTok{eset    }\OtherTok{\textless{}{-}}\FunctionTok{exprs}\NormalTok{(eset)}
\NormalTok{eset[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{,}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           GSM1523727 GSM1523728 GSM1523729 GSM1523744 GSM1523745
## 1007_s_at  3.2176645  3.0624323  3.0279131   2.921683  2.8456013
## 1053_at    2.4050109  2.4394879  2.2442708   2.345916  2.4328582
## 117_at     1.4933412  1.8067380  1.5959665   1.839822  1.8326058
## 121_at     2.1965561  2.2812181  2.1865556   2.258599  2.1874363
## 1255_g_at  0.8698382  0.9502466  0.8125414   1.012860  0.9441993
\end{verbatim}

Annotation of genes in the expression matrix and removal of duplicate genes.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(IOBR)}

\CommentTok{\# Load the annotation file \textasciigrave{}anno\_hug133plus2\textasciigrave{} in IOBR.}
\FunctionTok{head}\NormalTok{(anno\_hug133plus2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 2
##   probe_id  symbol 
##   <fct>     <fct>  
## 1 1007_s_at MIR4640
## 2 1053_at   RFC2   
## 3 117_at    HSPA6  
## 4 121_at    PAX8   
## 5 1255_g_at GUCA1A 
## 6 1294_at   MIR5193
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Conduct gene annotation using \textasciigrave{}anno\_hug133plus2\textasciigrave{} file; If identical gene symbols exists, these genes would be ordered by the mean expression levels. The gene symbol with highest mean expression level is selected and remove others. }

\NormalTok{eset}\OtherTok{\textless{}{-}}\FunctionTok{anno\_eset}\NormalTok{(}\AttributeTok{eset       =}\NormalTok{ eset,}
                \AttributeTok{annotation =}\NormalTok{ anno\_hug133plus2,}
                \AttributeTok{symbol     =} \StringTok{"symbol"}\NormalTok{,}
                \AttributeTok{probe      =} \StringTok{"probe\_id"}\NormalTok{,}
                \AttributeTok{method     =} \StringTok{"mean"}\NormalTok{)}
\NormalTok{eset[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              GSM1523727 GSM1523728 GSM1523729
## SH3KBP1        4.327974   4.316195   4.351425
## RPL41          4.246149   4.246808   4.257940
## EEF1A1         4.293762   4.291038   4.262199
## COX2           4.250288   4.283714   4.270508
## LOC101928826   4.219303   4.219670   4.213252
\end{verbatim}

\hypertarget{available-methods-to-decode-tme-contexture}{%
\section{Available Methods to Decode TME Contexture}\label{available-methods-to-decode-tme-contexture}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tme\_deconvolution\_methods}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         MCPcounter               EPIC              xCell          CIBERSORT 
##       "mcpcounter"             "epic"            "xcell"        "cibersort" 
## CIBERSORT Absolute                IPS           ESTIMATE                SVR 
##    "cibersort_abs"              "ips"         "estimate"              "svr" 
##               lsei              TIMER          quanTIseq 
##             "lsei"            "timer"        "quantiseq"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Return available parameter options of deconvolution methods}
\end{Highlighting}
\end{Shaded}

The input data is a matrix subseted from ESET of ACRG cohort, with genes in rows and samples in columns. The row name must be HGNC symbols and the column name must be sample names.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{eset\_acrg }\OtherTok{\textless{}{-}}\NormalTok{ eset[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{50}\NormalTok{]}
\NormalTok{eset\_acrg[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              GSM1523727 GSM1523728 GSM1523729
## SH3KBP1        4.327974   4.316195   4.351425
## RPL41          4.246149   4.246808   4.257940
## EEF1A1         4.293762   4.291038   4.262199
## COX2           4.250288   4.283714   4.270508
## LOC101928826   4.219303   4.219670   4.213252
\end{verbatim}

Check detail parameters of the function

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# help(deconvo\_tme)}
\end{Highlighting}
\end{Shaded}

\hypertarget{method-1-cibersort}{%
\section{Method 1: CIBERSORT}\label{method-1-cibersort}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cibersort}\OtherTok{\textless{}{-}}\FunctionTok{deconvo\_tme}\NormalTok{(}\AttributeTok{eset =}\NormalTok{ eset\_acrg, }\AttributeTok{method =} \StringTok{"cibersort"}\NormalTok{, }\AttributeTok{arrays =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{perm =} \DecValTok{100}\NormalTok{ )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## >>> Running CIBERSORT
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# head(cibersort)}
\NormalTok{res}\OtherTok{\textless{}{-}}\FunctionTok{cell\_bar\_plot}\NormalTok{(}\AttributeTok{input =}\NormalTok{ cibersort[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{12}\NormalTok{,], }\AttributeTok{title =} \StringTok{"CIBERSORT Cell Fraction"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## There are seven categories you can choose: box, continue2, continue, random, heatmap, heatmap3, tidyheatmap
\end{verbatim}

\begin{verbatim}
## >>>>=== Palette option for random: 1: palette1; 2: palette2; 3: palette3;  4: palette4
\end{verbatim}

\includegraphics{_main_files/figure-latex/unnamed-chunk-50-1.pdf}

\hypertarget{method-2-epic}{%
\subsection{Method 2: EPIC}\label{method-2-epic}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# help(deconvo\_epic)}
\NormalTok{epic}\OtherTok{\textless{}{-}}\FunctionTok{deconvo\_tme}\NormalTok{(}\AttributeTok{eset =}\NormalTok{ eset\_acrg, }\AttributeTok{method =} \StringTok{"epic"}\NormalTok{, }\AttributeTok{arrays =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## >>> Running EPIC
\end{verbatim}

\begin{verbatim}
## Warning in IOBR::EPIC(bulk = eset, reference = ref, mRNA_cell = NULL, scaleExprs = TRUE): The optimization didn't fully converge for some samples:
## GSM1523744; GSM1523746; GSM1523781; GSM1523786
##  - check fit.gof for the convergeCode and convergeMessage
\end{verbatim}

\begin{verbatim}
## Warning in IOBR::EPIC(bulk = eset, reference = ref, mRNA_cell = NULL, scaleExprs
## = TRUE): mRNA_cell value unknown for some cell types: CAFs, Endothelial - using
## the default value of 0.4 for these but this might bias the true cell proportions
## from all cell types.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(epic)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 9
##   ID      Bcells_EPIC CAFs_EPIC CD4_Tcells_EPIC CD8_Tcells_EPIC Endothelial_EPIC
##   <chr>         <dbl>     <dbl>           <dbl>           <dbl>            <dbl>
## 1 GSM152~      0.0292   0.00888           0.145          0.0756           0.0876
## 2 GSM152~      0.0293   0.0109            0.159          0.0745           0.0954
## 3 GSM152~      0.0308   0.0106            0.149          0.0732           0.0941
## 4 GSM152~      0.0273   0.0108            0.145          0.0704           0.0860
## 5 GSM152~      0.0280   0.0111            0.151          0.0707           0.0928
## 6 GSM152~      0.0320   0.00958           0.148          0.0716           0.0907
## # i 3 more variables: Macrophages_EPIC <dbl>, NKcells_EPIC <dbl>,
## #   otherCells_EPIC <dbl>
\end{verbatim}

\hypertarget{method-3-mcpcounter}{%
\section{Method 3: MCPcounter}\label{method-3-mcpcounter}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mcp}\OtherTok{\textless{}{-}}\FunctionTok{deconvo\_tme}\NormalTok{(}\AttributeTok{eset =}\NormalTok{ eset\_acrg, }\AttributeTok{method =} \StringTok{"mcpcounter"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## >>> Running MCP-counter
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(mcp)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 11
##   ID         T_cells_MCPcounter CD8_T_cells_MCPcounter Cytotoxic_lymphocytes_M~1
##   <chr>                   <dbl>                  <dbl>                     <dbl>
## 1 GSM1523727               1.47                  1.11                       1.33
## 2 GSM1523728               1.53                  1.05                       1.60
## 3 GSM1523729               1.47                  1.07                       1.37
## 4 GSM1523744               1.46                  1.02                       1.44
## 5 GSM1523745               1.51                  1.10                       1.49
## 6 GSM1523746               1.51                  0.992                      1.40
## # i abbreviated name: 1: Cytotoxic_lymphocytes_MCPcounter
## # i 7 more variables: B_lineage_MCPcounter <dbl>, NK_cells_MCPcounter <dbl>,
## #   Monocytic_lineage_MCPcounter <dbl>,
## #   Myeloid_dendritic_cells_MCPcounter <dbl>, Neutrophils_MCPcounter <dbl>,
## #   Endothelial_cells_MCPcounter <dbl>, Fibroblasts_MCPcounter <dbl>
\end{verbatim}

\hypertarget{method-4-xcell}{%
\subsection{Method 4: xCELL}\label{method-4-xcell}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{xcell}\OtherTok{\textless{}{-}}\FunctionTok{deconvo\_tme}\NormalTok{(}\AttributeTok{eset =}\NormalTok{ eset\_acrg, }\AttributeTok{method =} \StringTok{"xcell"}\NormalTok{, }\AttributeTok{arrays =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(xcell)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 68
##   ID         aDC_xCell Adipocytes_xCell Astrocytes_xCell `B-cells_xCell`
##   <chr>          <dbl>            <dbl>            <dbl>           <dbl>
## 1 GSM1523727  4.78e-19          0.0250          0                 0     
## 2 GSM1523728  9.41e- 2          0.00433         7.70e- 3          0     
## 3 GSM1523729  1.02e- 1          0.0789          2.04e- 2          0     
## 4 GSM1523744  7.88e- 2          0.0538          4.82e-18          0.0126
## 5 GSM1523745  9.02e- 2          0.0136          1.93e- 2          0     
## 6 GSM1523746  3.40e- 2          0.0331          9.22e- 2          0     
## # i 63 more variables: Basophils_xCell <dbl>,
## #   `CD4+_memory_T-cells_xCell` <dbl>, `CD4+_naive_T-cells_xCell` <dbl>,
## #   `CD4+_T-cells_xCell` <dbl>, `CD4+_Tcm_xCell` <dbl>, `CD4+_Tem_xCell` <dbl>,
## #   `CD8+_naive_T-cells_xCell` <dbl>, `CD8+_T-cells_xCell` <dbl>,
## #   `CD8+_Tcm_xCell` <dbl>, `CD8+_Tem_xCell` <dbl>, cDC_xCell <dbl>,
## #   Chondrocytes_xCell <dbl>, `Class-switched_memory_B-cells_xCell` <dbl>,
## #   CLP_xCell <dbl>, CMP_xCell <dbl>, DC_xCell <dbl>, ...
\end{verbatim}

\hypertarget{method-5-estimate}{%
\section{Method 5: ESTIMATE}\label{method-5-estimate}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{estimate}\OtherTok{\textless{}{-}}\FunctionTok{deconvo\_tme}\NormalTok{(}\AttributeTok{eset =}\NormalTok{ eset\_acrg, }\AttributeTok{method =} \StringTok{"estimate"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Merged dataset includes 9940 genes (472 mismatched)."
## [1] "1 gene set: StromalSignature  overlap= 136"
## [1] "2 gene set: ImmuneSignature  overlap= 138"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(estimate)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 5
##   ID         StromalScore_estimate ImmuneScore_estimate ESTIMATEScore_estimate
##   <chr>                      <dbl>                <dbl>                  <dbl>
## 1 GSM1523727                -1250.                 268.                 -982. 
## 2 GSM1523728                  197.                1334.                 1531. 
## 3 GSM1523729                 -111.                 822.                  711. 
## 4 GSM1523744                 -119.                 662.                  544. 
## 5 GSM1523745                  324.                1015.                 1339. 
## 6 GSM1523746                 -594.                 621.                   27.0
## # i 1 more variable: TumorPurity_estimate <dbl>
\end{verbatim}

\hypertarget{method-6-timer}{%
\section{Method 6: TIMER}\label{method-6-timer}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{timer}\OtherTok{\textless{}{-}}\FunctionTok{deconvo\_tme}\NormalTok{(}\AttributeTok{eset =}\NormalTok{ eset\_acrg, }\AttributeTok{method =} \StringTok{"timer"}\NormalTok{, }\AttributeTok{group\_list =} \FunctionTok{rep}\NormalTok{(}\StringTok{"stad"}\NormalTok{,}\FunctionTok{dim}\NormalTok{(eset\_acrg)[}\DecValTok{2}\NormalTok{]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Outlier genes: AGR2 B2M COL1A2 COL3A1 COX2 CYAT1 EEF1A1 EIF1 FTH1 GKN1 HUWE1 IGK IGLC1 LIPF LOC101060363 LOC101928826 MIR8071-2 ND4 PABPC1 PABPC3 PGA4 RPL13AP5 RPL37 RPL37A RPL41 RPL7 RPS10 RPS16 RPS17 RPS18 RPS19 S100A6 S100A9 SH3KBP1 SNORD24 SNORD42A SNORD54 SNORD73A SPINK1 SPINK4 TFF1 UQCRFS1"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(timer)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 7
##   ID         B_cell_TIMER T_cell_CD4_TIMER T_cell_CD8_TIMER Neutrophil_TIMER
##   <chr>             <dbl>            <dbl>            <dbl>            <dbl>
## 1 GSM1523727        0.104            0.128            0.183            0.108
## 2 GSM1523728        0.103            0.130            0.192            0.118
## 3 GSM1523729        0.106            0.130            0.190            0.110
## 4 GSM1523744        0.101            0.126            0.187            0.111
## 5 GSM1523745        0.104            0.127            0.191            0.116
## 6 GSM1523746        0.105            0.129            0.192            0.111
## # i 2 more variables: Macrophage_TIMER <dbl>, DC_TIMER <dbl>
\end{verbatim}

\hypertarget{method-7-quantiseq}{%
\section{Method 7: quanTIseq}\label{method-7-quantiseq}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{quantiseq}\OtherTok{\textless{}{-}}\FunctionTok{deconvo\_tme}\NormalTok{(}\AttributeTok{eset =}\NormalTok{ eset\_acrg, }\AttributeTok{tumor =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{arrays =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{scale\_mrna =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{method =} \StringTok{"quantiseq"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Running quanTIseq deconvolution module
\end{verbatim}

\begin{verbatim}
## Gene expression normalization and re-annotation (arrays: TRUE)
\end{verbatim}

\begin{verbatim}
## Removing 17 genes with high expression in tumors
\end{verbatim}

\begin{verbatim}
## Signature genes found in data set: 152/153 (99.35%)
\end{verbatim}

\begin{verbatim}
## Mixture deconvolution (method: lsei)
\end{verbatim}

\begin{verbatim}
## Deconvolution sucessful!
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(quantiseq)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 12
##   ID         B_cells_quantiseq Macrophages_M1_quantiseq Macrophages_M2_quantiseq
##   <chr>                  <dbl>                    <dbl>                    <dbl>
## 1 GSM1523727            0.0983                   0.0510                   0.0598
## 2 GSM1523728            0.0967                   0.0795                   0.0607
## 3 GSM1523729            0.102                    0.0450                   0.0758
## 4 GSM1523744            0.0954                   0.0725                   0.0579
## 5 GSM1523745            0.0991                   0.0669                   0.0613
## 6 GSM1523746            0.105                    0.0453                   0.0662
## # i 8 more variables: Monocytes_quantiseq <dbl>, Neutrophils_quantiseq <dbl>,
## #   NK_cells_quantiseq <dbl>, T_cells_CD4_quantiseq <dbl>,
## #   T_cells_CD8_quantiseq <dbl>, Tregs_quantiseq <dbl>,
## #   Dendritic_cells_quantiseq <dbl>, Other_quantiseq <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res}\OtherTok{\textless{}{-}}\FunctionTok{cell\_bar\_plot}\NormalTok{(}\AttributeTok{input =}\NormalTok{ quantiseq[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{12}\NormalTok{, ], }\AttributeTok{title =} \StringTok{"quanTIseq Cell Fraction"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## There are seven categories you can choose: box, continue2, continue, random, heatmap, heatmap3, tidyheatmap
\end{verbatim}

\begin{verbatim}
## >>>>=== Palette option for random: 1: palette1; 2: palette2; 3: palette3;  4: palette4
\end{verbatim}

\includegraphics{_main_files/figure-latex/unnamed-chunk-57-1.pdf}

\hypertarget{method-8-ips}{%
\section{8) Method 8: IPS}\label{method-8-ips}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ips}\OtherTok{\textless{}{-}}\FunctionTok{deconvo\_tme}\NormalTok{(}\AttributeTok{eset =}\NormalTok{ eset\_acrg, }\AttributeTok{method =} \StringTok{"ips"}\NormalTok{, }\AttributeTok{plot=} \ConstantTok{FALSE}\NormalTok{)}
\FunctionTok{head}\NormalTok{(ips)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 7
##   ID         MHC_IPS EC_IPS SC_IPS  CP_IPS AZ_IPS IPS_IPS
##   <chr>        <dbl>  <dbl>  <dbl>   <dbl>  <dbl>   <dbl>
## 1 GSM1523727    2.25  0.404 -0.192  0.220    2.68       9
## 2 GSM1523728    2.37  0.608 -0.578 -0.234    2.17       7
## 3 GSM1523729    2.10  0.480 -0.322  0.0993   2.36       8
## 4 GSM1523744    2.12  0.535 -0.333  0.0132   2.34       8
## 5 GSM1523745    1.91  0.559 -0.479  0.0880   2.08       7
## 6 GSM1523746    1.94  0.458 -0.346  0.261    2.31       8
\end{verbatim}

\hypertarget{combination-of-above-deconvolution-results}{%
\section{9) Combination of above deconvolution results}\label{combination-of-above-deconvolution-results}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tme\_combine}\OtherTok{\textless{}{-}}\NormalTok{cibersort }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{inner\_join}\NormalTok{(.,mcp,}\AttributeTok{by       =} \StringTok{"ID"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{inner\_join}\NormalTok{(.,xcell,}\AttributeTok{by     =} \StringTok{"ID"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{inner\_join}\NormalTok{(.,epic,}\AttributeTok{by      =} \StringTok{"ID"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{inner\_join}\NormalTok{(.,estimate,}\AttributeTok{by  =} \StringTok{"ID"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{inner\_join}\NormalTok{(.,timer,}\AttributeTok{by     =} \StringTok{"ID"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{inner\_join}\NormalTok{(.,quantiseq,}\AttributeTok{by =} \StringTok{"ID"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{inner\_join}\NormalTok{(.,ips,}\AttributeTok{by       =} \StringTok{"ID"}\NormalTok{)}
\FunctionTok{dim}\NormalTok{(tme\_combine)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  50 138
\end{verbatim}

If you use this package in your work, please cite both our package and the method(s) you are using.

\hypertarget{licenses-of-the-deconvolution-methods}{%
\section{Licenses of the deconvolution methods}\label{licenses-of-the-deconvolution-methods}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2963}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.3704}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
method
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
license
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
citation
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\href{https://cibersort.stanford.edu/}{CIBERSORT} & free for non-commerical use only & Newman, A. M., Liu, C. L., Green, M. R., Gentles, A. J., Feng, W., Xu, Y., \ldots{} Alizadeh, A. A. (2015). Robust enumeration of cell subsets from tissue expression profiles. Nature Methods, 12(5), 453--457. \url{https://doi.org/10.1038/nmeth.3337} \\
\href{https://bioinformatics.mdanderson.org/public-software/estimate/}{ESTIMATE} & free (\href{https://bioinformatics.mdanderson.org/estimate/}{GPL2.0}) & Vegesna R, Kim H, Torres-Garcia W, \ldots, Verhaak R. (2013). Inferring tumour purity and stromal and immune cell admixture from expression data. Nature Communications 4, 2612. \url{http://doi.org/10.1038/ncomms3612} \\
\href{http://icbi.at/software/quantiseq/doc/index.html}{quanTIseq} & free (\href{https://github.com/icbi-lab/immunedeconv/blob/master/LICENSE.md}{BSD}) & Finotello, F., Mayer, C., Plattner, C., Laschober, G., Rieder, D., Hackl, H., \ldots, Sopper, S. (2019). Molecular and pharmacological modulators of the tumor immune contexture revealed by deconvolution of RNA-seq data. Genome medicine, 11(1), 34. \url{https://doi.org/10.1186/s13073-019-0638-6} \\
\href{http://cistrome.org/TIMER/}{TIMER} & free (\href{http://cistrome.org/TIMER/download.html}{GPL 2.0}) & Li, B., Severson, E., Pignon, J.-C., Zhao, H., Li, T., Novak, J., \ldots{} Liu, X. S. (2016). Comprehensive analyses of tumor immunity: implications for cancer immunotherapy. Genome Biology, 17(1), 174. \url{https://doi.org/10.1186/s13059-016-1028-7} \\
\href{https://github.com/icbi-lab/Immunophenogram}{IPS} & free (\href{https://github.com/icbi-lab/Immunophenogram/blob/master/LICENSE}{BSD}) & P. Charoentong et al., Pan-cancer Immunogenomic Analyses Reveal Genotype-Immunophenotype Relationships and Predictors of Response to Checkpoint Blockade. Cell Reports 18, 248-262 (2017). \url{https://doi.org/10.1016/j.celrep.2016.12.019} \\
\href{https://github.com/ebecht/MCPcounter}{MCPCounter} & free (\href{https://github.com/ebecht/MCPcounter/blob/master/Source/License}{GPL 3.0}) & Becht, E., Giraldo, N. A., Lacroix, L., Buttard, B., Elarouci, N., Petitprez, F., \ldots{} de Reyniès, A. (2016). Estimating the population abundance of tissue-infiltrating immune and stromal cell populations using gene expression. Genome Biology, 17(1), 218. \url{https://doi.org/10.1186/s13059-016-1070-5} \\
\href{http://xcell.ucsf.edu/}{xCell} & free (\href{https://github.com/dviraran/xCell/blob/master/DESCRIPTION}{GPL 3.0}) & Aran, D., Hu, Z., \& Butte, A. J. (2017). xCell: digitally portraying the tissue cellular heterogeneity landscape. Genome Biology, 18(1), 220. \url{https://doi.org/10.1186/s13059-017-1349-1} \\
\href{https://gfellerlab.shinyapps.io/EPIC_1-1/}{EPIC} & free for non-commercial use only (\href{https://github.com/GfellerLab/EPIC/blob/master/LICENSE}{Academic License}) & Racle, J., de Jonge, K., Baumgaertner, P., Speiser, D. E., \& Gfeller, D. (2017). Simultaneous enumeration of cancer and immune cell types from bulk tumor gene expression data. ELife, 6, e26476. \url{https://doi.org/10.7554/eLife.26476} \\
\end{longtable}

\hypertarget{licenses-of-the-signature-esitmation-method}{%
\subsection{Licenses of the signature-esitmation method}\label{licenses-of-the-signature-esitmation-method}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.2963}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.3704}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
method
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
license
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
citation
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\href{http://www.bioconductor.org/packages/release/bioc/html/GSVA.html}{GSVA} & free (\href{https://github.com/rcastelo/GSVA}{GPL (\textgreater= 2)}) & Hänzelmann S, Castelo R, Guinney J (2013). ``GSVA: gene set variation analysis for microarray and RNA-Seq data.'' BMC Bioinformatics, 14, 7. doi: 10.1186/1471-2105-14-7, \url{http://www.biomedcentral.com/1471-2105/14/7} \\
\end{longtable}

\hypertarget{cross}{%
\chapter{Cross-references}\label{cross}}

Cross-references make it easier for your readers to find and link to elements in your book.

\hypertarget{chapters-and-sub-chapters}{%
\section{Chapters and sub-chapters}\label{chapters-and-sub-chapters}}

There are two steps to cross-reference any heading:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Label the heading: \texttt{\#\ Hello\ world\ \{\#nice-label\}}.

  \begin{itemize}
  \tightlist
  \item
    Leave the label off if you like the automated heading generated based on your heading title: for example, \texttt{\#\ Hello\ world} = \texttt{\#\ Hello\ world\ \{\#hello-world\}}.
  \item
    To label an un-numbered heading, use: \texttt{\#\ Hello\ world\ \{-\#nice-label\}} or \texttt{\{\#\ Hello\ world\ .unnumbered\}}.
  \end{itemize}
\item
  Next, reference the labeled heading anywhere in the text using \texttt{\textbackslash{}@ref(nice-label)}; for example, please see Chapter \ref{cross}.

  \begin{itemize}
  \tightlist
  \item
    If you prefer text as the link instead of a numbered reference use: \protect\hyperlink{cross}{any text you want can go here}.
  \end{itemize}
\end{enumerate}

\hypertarget{captioned-figures-and-tables}{%
\section{Captioned figures and tables}\label{captioned-figures-and-tables}}

Figures and tables \emph{with captions} can also be cross-referenced from elsewhere in your book using \texttt{\textbackslash{}@ref(fig:chunk-label)} and \texttt{\textbackslash{}@ref(tab:chunk-label)}, respectively.

See Figure \ref{fig:nice-fig}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{, }\DecValTok{4}\NormalTok{, .}\DecValTok{1}\NormalTok{, .}\DecValTok{1}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(pressure, }\AttributeTok{type =} \StringTok{\textquotesingle{}b\textquotesingle{}}\NormalTok{, }\AttributeTok{pch =} \DecValTok{19}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}

{\centering \includegraphics[width=0.8\linewidth]{_main_files/figure-latex/nice-fig-1} 

}

\caption{Here is a nice figure!}\label{fig:nice-fig}
\end{figure}

Don't miss Table \ref{tab:nice-tab}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}
  \FunctionTok{head}\NormalTok{(pressure, }\DecValTok{10}\NormalTok{), }\AttributeTok{caption =} \StringTok{\textquotesingle{}Here is a nice table!\textquotesingle{}}\NormalTok{,}
  \AttributeTok{booktabs =} \ConstantTok{TRUE}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}

\caption{\label{tab:nice-tab}Here is a nice table!}
\centering
\begin{tabular}[t]{rr}
\toprule
temperature & pressure\\
\midrule
0 & 0.0002\\
20 & 0.0012\\
40 & 0.0060\\
60 & 0.0300\\
80 & 0.0900\\
\addlinespace
100 & 0.2700\\
120 & 0.7500\\
140 & 1.8500\\
160 & 4.2000\\
180 & 8.8000\\
\bottomrule
\end{tabular}
\end{table}

\hypertarget{footnotes-and-citations}{%
\chapter{Footnotes and citations}\label{footnotes-and-citations}}

\hypertarget{footnotes}{%
\section{Footnotes}\label{footnotes}}

Footnotes are put inside the square brackets after a caret \texttt{\^{}{[}{]}}. Like this one \footnote{This is a footnote.}.

\hypertarget{citations}{%
\section{Citations}\label{citations}}

Reference items in your bibliography file(s) using \texttt{@key}.

For example, we are using the \textbf{bookdown} package \citep{R-bookdown} (check out the last code chunk in index.Rmd to see how this citation key was added) in this sample book, which was built on top of R Markdown and \textbf{knitr} \citep{xie2015} (this citation was added manually in an external file book.bib).
Note that the \texttt{.bib} files need to be listed in the index.Rmd with the YAML \texttt{bibliography} key.

The RStudio Visual Markdown Editor can also make it easier to insert citations: \url{https://rstudio.github.io/visual-markdown-editing/\#/citations}

\hypertarget{blocks}{%
\chapter{Blocks}\label{blocks}}

\hypertarget{equations}{%
\section{Equations}\label{equations}}

Here is an equation.

\begin{equation} 
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  \label{eq:binom}
\end{equation}

You may refer to using \texttt{\textbackslash{}@ref(eq:binom)}, like see Equation \eqref{eq:binom}.

\hypertarget{theorems-and-proofs}{%
\section{Theorems and proofs}\label{theorems-and-proofs}}

Labeled theorems can be referenced in text using \texttt{\textbackslash{}@ref(thm:tri)}, for example, check out this smart theorem \ref{thm:tri}.

\begin{theorem}
\protect\hypertarget{thm:tri}{}\label{thm:tri}For a right triangle, if \(c\) denotes the \emph{length} of the hypotenuse
and \(a\) and \(b\) denote the lengths of the \textbf{other} two sides, we have
\[a^2 + b^2 = c^2\]
\end{theorem}

Read more here \url{https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html}.

\hypertarget{callout-blocks}{%
\section{Callout blocks}\label{callout-blocks}}

The R Markdown Cookbook provides more help on how to use custom blocks to design your own callouts: \url{https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html}

\hypertarget{sharing-your-book}{%
\chapter{Sharing your book}\label{sharing-your-book}}

\hypertarget{publishing}{%
\section{Publishing}\label{publishing}}

HTML books can be published online, see: \url{https://bookdown.org/yihui/bookdown/publishing.html}

\hypertarget{pages}{%
\section{404 pages}\label{pages}}

By default, users will be directed to a 404 page if they try to access a webpage that cannot be found. If you'd like to customize your 404 page instead of using the default, you may add either a \texttt{\_404.Rmd} or \texttt{\_404.md} file to your project root and use code and/or Markdown syntax.

\hypertarget{metadata-for-sharing}{%
\section{Metadata for sharing}\label{metadata-for-sharing}}

Bookdown HTML books will provide HTML metadata for social sharing on platforms like Twitter, Facebook, and LinkedIn, using information you provide in the \texttt{index.Rmd} YAML. To setup, set the \texttt{url} for your book and the path to your \texttt{cover-image} file. Your book's \texttt{title} and \texttt{description} are also used.

This \texttt{gitbook} uses the same social sharing data across all chapters in your book- all links shared will look the same.

Specify your book's source repository on GitHub using the \texttt{edit} key under the configuration options in the \texttt{\_output.yml} file, which allows users to suggest an edit by linking to a chapter's source file.

Read more about the features of this output format here:

\url{https://pkgs.rstudio.com/bookdown/reference/gitbook.html}

Or use:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{?bookdown}\SpecialCharTok{::}\NormalTok{gitbook}
\end{Highlighting}
\end{Shaded}

\hypertarget{references}{%
\chapter{References}\label{references}}

If IOBR R package is utilized in your published research, please cite:

Zeng D, Ye Z, Shen R, Yu G, Wu J, Xiong Y,\ldots, Liao W (2021) \textbf{IOBR}: Multi-Omics Immuno-Oncology Biological Research to Decode Tumor Microenvironment and Signatures. \emph{Frontiers in Immunology}. 12:687975. \href{https://www.frontiersin.org/articles/10.3389/fimmu.2021.687975/full}{doi: 10.3389/fimmu.2021.687975}

\hypertarget{tme-deconvolution-1}{%
\section{TME deconvolution}\label{tme-deconvolution-1}}

Please cite the following papers appropriately for TME deconvolution algorithm if used:

\textbf{CIBERSORT}: Newman, A. M., Liu, C. L., Green, M. R., Gentles, A. J., Feng, W., Xu, Y., \ldots{} Alizadeh, A. A. (2015). Robust enumeration of cell subsets from tissue expression profiles. Nature Methods, 12(5), 453--457. \url{https://doi.org/10.1038/nmeth.3337}

\textbf{ESTIMATE}: Vegesna R, Kim H, Torres-Garcia W, \ldots, Verhaak R.*(2013). Inferring tumour purity and stromal and immune cell admixture from expression data. Nature Communications 4, 2612. \url{http://doi.org/10.1038/ncomms3612}

\textbf{quanTIseq}: Finotello, F., Mayer, C., Plattner, C., Laschober, G., Rieder, D., Hackl, H., \ldots, Sopper, S.* (2019). Molecular and pharmacological modulators of the tumor immune contexture revealed by deconvolution of RNA-seq data. Genome medicine, 11(1), 34. \url{https://doi.org/10.1186/s13073-019-0638-6}

\textbf{TIMER}: Li, B., Severson, E., Pignon, J.-C., Zhao, H., Li, T., Novak, J., \ldots{} Liu, X. S.* (2016). Comprehensive analyses of tumor immunity: implications for cancer immunotherapy. Genome Biology, 17(1), 174.

\textbf{IPS}: P. Charoentong et al.*, Pan-cancer Immunogenomic Analyses Reveal Genotype-Immunophenotype Relationships and Predictors of Response to Checkpoint Blockade. Cell Reports 18, 248-262 (2017). \url{https://doi.org/10.1016/j.celrep.2016.12.019}

\textbf{MCPCounter}: Becht, E., Giraldo, N. A., Lacroix, L., Buttard, B., Elarouci, N., Petitprez, F., \ldots{} de Reyniès, A*. (2016). Estimating the population abundance of tissue-infiltrating immune and stromal cell populations using gene expression. Genome Biology, 17(1), 218. \url{https://doi.org/10.1186/s13059-016-1070-5}

\textbf{xCell}: Aran, D., Hu, Z., \& Butte, A. J.* (2017). xCell: digitally portraying the tissue cellular heterogeneity landscape. Genome Biology, 18(1), 220. \url{https://doi.org/10.1186/s13059-017-1349-1}

\textbf{EPIC}: Racle, J., de Jonge, K., Baumgaertner, P., Speiser, D. E., \& Gfeller, D*. (2017). Simultaneous enumeration of cancer and immune cell types from bulk tumor gene expression data. ELife, 6, e26476. \url{https://doi.org/10.7554/eLife.26476}

\hypertarget{tme-signatures}{%
\section{TME Signatures}\label{tme-signatures}}

For signature score estimation, please cite corresponding literature below:

\textbf{ssgsea}: Barbie, D.A. et al (2009). Systematic RNA interference reveals that oncogenic KRAS-driven cancers require TBK1. Nature, 462(5):108-112.

\textbf{gsva}: Hänzelmann, S., Castelo, R. and Guinney, J. (2013). GSVA: Gene set variation analysis for microarray and RNA-Seq data. BMC Bioinformatics, 14(1):7.

\textbf{zscore}: Lee, E. et al (2008). Inferring pathway activity toward precise disease classification. PLoS Comp Biol, 4(11):e1000217.

\hypertarget{data-sets}{%
\section{Data sets}\label{data-sets}}

For the datasets enrolled in IOBR, please cite the data sources:

\textbf{UCSCXena}: Wang et al.,et al (2019). The UCSCXenaTools R package: a toolkit for accessing genomics data from UCSC Xena platform, from cancer multi-omics to single-cell RNA-seq. Journal of Open Source Software, 4(40), 1627

\textbf{TLSscore}: Helmink BA, Reddy SM, Gao J, et al.~B cells and tertiary lymphoid structures promote immunotherapy response. Nature. 2020 Jan;577(7791):549-555.

\textbf{IMvigor210 immuntherapy cohort}: Mariathasan S, Turley SJ, Nickles D, et al.~TGFβ attenuates tumour response to PD-L1 blockade by contributing to exclusion of T cells. Nature. 2018 Feb 22;554(7693):544-548.
\textbf{HCP5}: Kulski, J.K. Long Noncoding RNA HCP5, a Hybrid HLA Class I Endogenous Retroviral Gene: Structure, Expression, and Disease Associations. Cells 2019, 8, 480.

\textbf{HCP5}: Li, Y., Jiang, T., Zhou, W. et al.~Pan-cancer characterization of immune-related lncRNAs identifies potential oncogenic biomarkers. Nat Commun 11, 1000 (2020).
HCP5: Sun J, Zhang Z, Bao S, et alIdentification of tumor immune infiltration-associated lncRNAs for improving prognosis and immunotherapy response of patients with non-small cell lung cancerJournal for ImmunoTherapy of Cancer 2020;8:e000110.

\textbf{LINC00657}: Feng Q, Zhang H, Yao D, Chen WD, Wang YD. Emerging Role of Non-Coding RNAs in Esophageal Squamous Cell Carcinoma. Int J Mol Sci. 2019 Dec 30;21(1):258. doi: 10.3390/ijms21010258.

\textbf{LINC00657}: Qin X, Zhou M, Lv H, Mao X, Li X, Guo H, Li L, Xing H. Long noncoding RNA LINC00657 inhibits cervical cancer development by sponging miR-20a-5p and targeting RUNX3. Cancer Lett. 2020 Oct 28:S0304-3835(20)30578-4. doi: 10.1016/j.canlet.2020.10.044.
\textbf{LINC00657}: Zhang XM, Wang J, Liu ZL, Liu H, Cheng YF, Wang T. LINC00657/miR-26a-5p/CKS2 ceRNA network promotes the growth of esophageal cancer cells via the MDM2/p53/Bcl2/Bax pathway. Biosci Rep.~2020;40(6):BSR20200525.

\textbf{TCGA-STAD}: Cancer Genome Atlas Research Network. Comprehensive molecular characterization of gastric adenocarcinoma. Nature. 2014 Sep 11;513(7517):202-9. doi: 10.1038/nature13480.
TCGA.STAD MAF data: \url{https://api.gdc.cancer.gov/data/c06465a3-50e7-46f7-b2dd-7bd654ca206b}

\hypertarget{others}{%
\section{Others}\label{others}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Newman, A. M., Liu, C. L., Green, M. R., Gentles, A. J., Feng, W., Xu, Y., \ldots{} Alizadeh, A. A. (2015). Robust enumeration of cell subsets from tissue expression profiles. Nature Methods, 12(5), 453--457.
\item
  Vegesna R, Kim H, Torres-Garcia W, \ldots, Verhaak R.*(2013). Inferring tumour purity and stromal and immune cell admixture from expression data. Nature Communications 4, 2612.
\item
  Rieder, D., Hackl, H., \ldots, Sopper, S.* (2019). Molecular and pharmacological modulators of the tumor immune contexture revealed by deconvolution of RNA-seq data. Genome medicine, 11(1), 34.
\item
  Li, B., Severson, E., Pignon, J.-C., Zhao, H., Li, T., Novak, J., \ldots{} Liu, X. S.* (2016). Comprehensive analyses of tumor immunity: implications for cancer immunotherapy. Genome Biology, 17(1), 174.
\item
  P. Charoentong et al.*, Pan-cancer Immunogenomic Analyses Reveal Genotype-Immunophenotype Relationships and Predictors of Response to Checkpoint Blockade. Cell Reports 18, 248-262 (2017).
\item
  Becht, E., Giraldo, N. A., Lacroix, L., Buttard, B., Elarouci, N., Petitprez, F., \ldots{} de Reyniès, A*. (2016). Estimating the population abundance of tissue-infiltrating immune and stromal cell populations using gene expression. Genome Biology, 17(1), 218.
\item
  Aran, D., Hu, Z., \& Butte, A. J.* (2017). xCell: digitally portraying the tissue cellular heterogeneity landscape. Genome Biology, 18(1), 220.
\item
  Racle, J., de Jonge, K., Baumgaertner, P., Speiser, D. E., \& Gfeller, D*. (2017). Simultaneous enumeration of cancer and immune cell types from bulk tumor gene expression data. ELife, 6, e26476.
\item
  Barbie, D.A. et al (2009). Systematic RNA interference reveals that oncogenic KRAS-driven cancers require TBK1. Nature, 462(5):108-112.
\item
  Hänzelmann, S., Castelo, R. and Guinney, J. (2013). GSVA: Gene set variation analysis for microarray and RNA-Seq data. BMC Bioinformatics, 14(1):7.
\item
  Lee, E. et al (2008). Inferring pathway activity toward precise disease classification. PLoS Comp Biol, 4(11):e1000217.
\item
  Wang et al.,et al (2019). The UCSCXenaTools R package: a toolkit for accessing genomics data from UCSC Xena platform, from cancer multi-omics to single-cell RNA-seq. Journal of Open Source Software, 4(40), 1627
\item
  Helmink BA, Reddy SM, Gao J, et al.~B cells and tertiary lymphoid structures promote immunotherapy response. Nature. 2020 Jan;577(7791):549-555.
\item
  Mariathasan S, Turley SJ, Nickles D, et al.~TGFβ attenuates tumour response to PD-L1 blockade by contributing to exclusion of T cells. Nature. 2018 Feb 22;554(7693):544-548.
\item
  Kulski, J.K. Long Noncoding RNA HCP5, a Hybrid HLA Class I Endogenous Retroviral Gene: Structure, Expression, and Disease Associations. Cells 2019, 8, 480.
\item
  Li, Y., Jiang, T., Zhou, W. et al.~Pan-cancer characterization of immune-related lncRNAs identifies potential oncogenic biomarkers. Nat Commun 11, 1000 (2020).
\item
  Sun J, Zhang Z, Bao S, et alIdentification of tumor immune infiltration-associated lncRNAs for improving prognosis and immunotherapy response of patients with non-small cell lung cancerJournal for ImmunoTherapy of Cancer 2020;8:e000110.
\item
  Feng Q, Zhang H, Yao D, Chen WD, Wang YD. Emerging Role of Non-Coding RNAs in Esophageal Squamous Cell Carcinoma. Int J Mol Sci. 2019 Dec 30;21(1):258. doi: 10.3390/ijms21010258.
\item
  Qin X, Zhou M, Lv H, Mao X, Li X, Guo H, Li L, Xing H. Long noncoding RNA LINC00657 inhibits cervical cancer development by sponging miR-20a-5p and targeting RUNX3. Cancer Lett. 2020 Oct
\item
  Zhang XM, Wang J, Liu ZL, Liu H, Cheng YF, Wang T. LINC00657/miR-26a-5p/CKS2 ceRNA network promotes the growth of esophageal cancer cells via the MDM2/p53/Bcl2/Bax pathway. Biosci Rep.~2020;40(6):BSR20200525.
\item
  Cancer Genome Atlas Research Network. Comprehensive molecular characterization of gastric adenocarcinoma. Nature. 2014 Sep 11;513(7517):202-9. doi: 10.1038/nature13480.
\end{enumerate}

  \bibliography{book.bib,packages.bib}

\end{document}
